// Code generated by ent, DO NOT EDIT.

package promptadminevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// Action applies equality check predicate on the "action" field. It's identical to ActionEQ.
func Action(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldAction, v))
}

// Scope applies equality check predicate on the "scope" field. It's identical to ScopeEQ.
func Scope(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldScope, v))
}

// TemplateID applies equality check predicate on the "template_id" field. It's identical to TemplateIDEQ.
func TemplateID(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldTemplateID, v))
}

// VersionID applies equality check predicate on the "version_id" field. It's identical to VersionIDEQ.
func VersionID(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldVersionID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldGroupID, v))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldAccountID, v))
}

// ActorID applies equality check predicate on the "actor_id" field. It's identical to ActorIDEQ.
func ActorID(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorName applies equality check predicate on the "actor_name" field. It's identical to ActorNameEQ.
func ActorName(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldActorName, v))
}

// RequestID applies equality check predicate on the "request_id" field. It's identical to RequestIDEQ.
func RequestID(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldRequestID, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// ActionEQ applies the EQ predicate on the "action" field.
func ActionEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldAction, v))
}

// ActionNEQ applies the NEQ predicate on the "action" field.
func ActionNEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldAction, v))
}

// ActionIn applies the In predicate on the "action" field.
func ActionIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldAction, vs...))
}

// ActionNotIn applies the NotIn predicate on the "action" field.
func ActionNotIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldAction, vs...))
}

// ActionGT applies the GT predicate on the "action" field.
func ActionGT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldAction, v))
}

// ActionGTE applies the GTE predicate on the "action" field.
func ActionGTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldAction, v))
}

// ActionLT applies the LT predicate on the "action" field.
func ActionLT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldAction, v))
}

// ActionLTE applies the LTE predicate on the "action" field.
func ActionLTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldAction, v))
}

// ActionContains applies the Contains predicate on the "action" field.
func ActionContains(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContains(FieldAction, v))
}

// ActionHasPrefix applies the HasPrefix predicate on the "action" field.
func ActionHasPrefix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasPrefix(FieldAction, v))
}

// ActionHasSuffix applies the HasSuffix predicate on the "action" field.
func ActionHasSuffix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasSuffix(FieldAction, v))
}

// ActionEqualFold applies the EqualFold predicate on the "action" field.
func ActionEqualFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEqualFold(FieldAction, v))
}

// ActionContainsFold applies the ContainsFold predicate on the "action" field.
func ActionContainsFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContainsFold(FieldAction, v))
}

// ScopeEQ applies the EQ predicate on the "scope" field.
func ScopeEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldScope, v))
}

// ScopeNEQ applies the NEQ predicate on the "scope" field.
func ScopeNEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldScope, v))
}

// ScopeIn applies the In predicate on the "scope" field.
func ScopeIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldScope, vs...))
}

// ScopeNotIn applies the NotIn predicate on the "scope" field.
func ScopeNotIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldScope, vs...))
}

// ScopeGT applies the GT predicate on the "scope" field.
func ScopeGT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldScope, v))
}

// ScopeGTE applies the GTE predicate on the "scope" field.
func ScopeGTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldScope, v))
}

// ScopeLT applies the LT predicate on the "scope" field.
func ScopeLT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldScope, v))
}

// ScopeLTE applies the LTE predicate on the "scope" field.
func ScopeLTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldScope, v))
}

// ScopeContains applies the Contains predicate on the "scope" field.
func ScopeContains(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContains(FieldScope, v))
}

// ScopeHasPrefix applies the HasPrefix predicate on the "scope" field.
func ScopeHasPrefix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasPrefix(FieldScope, v))
}

// ScopeHasSuffix applies the HasSuffix predicate on the "scope" field.
func ScopeHasSuffix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasSuffix(FieldScope, v))
}

// ScopeEqualFold applies the EqualFold predicate on the "scope" field.
func ScopeEqualFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEqualFold(FieldScope, v))
}

// ScopeContainsFold applies the ContainsFold predicate on the "scope" field.
func ScopeContainsFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContainsFold(FieldScope, v))
}

// TemplateIDEQ applies the EQ predicate on the "template_id" field.
func TemplateIDEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldTemplateID, v))
}

// TemplateIDNEQ applies the NEQ predicate on the "template_id" field.
func TemplateIDNEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldTemplateID, v))
}

// TemplateIDIn applies the In predicate on the "template_id" field.
func TemplateIDIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldTemplateID, vs...))
}

// TemplateIDNotIn applies the NotIn predicate on the "template_id" field.
func TemplateIDNotIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldTemplateID, vs...))
}

// TemplateIDGT applies the GT predicate on the "template_id" field.
func TemplateIDGT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldTemplateID, v))
}

// TemplateIDGTE applies the GTE predicate on the "template_id" field.
func TemplateIDGTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldTemplateID, v))
}

// TemplateIDLT applies the LT predicate on the "template_id" field.
func TemplateIDLT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldTemplateID, v))
}

// TemplateIDLTE applies the LTE predicate on the "template_id" field.
func TemplateIDLTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldTemplateID, v))
}

// TemplateIDIsNil applies the IsNil predicate on the "template_id" field.
func TemplateIDIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldTemplateID))
}

// TemplateIDNotNil applies the NotNil predicate on the "template_id" field.
func TemplateIDNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldTemplateID))
}

// VersionIDEQ applies the EQ predicate on the "version_id" field.
func VersionIDEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldVersionID, v))
}

// VersionIDNEQ applies the NEQ predicate on the "version_id" field.
func VersionIDNEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldVersionID, v))
}

// VersionIDIn applies the In predicate on the "version_id" field.
func VersionIDIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldVersionID, vs...))
}

// VersionIDNotIn applies the NotIn predicate on the "version_id" field.
func VersionIDNotIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldVersionID, vs...))
}

// VersionIDGT applies the GT predicate on the "version_id" field.
func VersionIDGT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldVersionID, v))
}

// VersionIDGTE applies the GTE predicate on the "version_id" field.
func VersionIDGTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldVersionID, v))
}

// VersionIDLT applies the LT predicate on the "version_id" field.
func VersionIDLT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldVersionID, v))
}

// VersionIDLTE applies the LTE predicate on the "version_id" field.
func VersionIDLTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldVersionID, v))
}

// VersionIDIsNil applies the IsNil predicate on the "version_id" field.
func VersionIDIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldVersionID))
}

// VersionIDNotNil applies the NotNil predicate on the "version_id" field.
func VersionIDNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldVersionID))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldGroupID))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldAccountID, v))
}

// AccountIDIsNil applies the IsNil predicate on the "account_id" field.
func AccountIDIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldAccountID))
}

// AccountIDNotNil applies the NotNil predicate on the "account_id" field.
func AccountIDNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldAccountID))
}

// ActorIDEQ applies the EQ predicate on the "actor_id" field.
func ActorIDEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldActorID, v))
}

// ActorIDNEQ applies the NEQ predicate on the "actor_id" field.
func ActorIDNEQ(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldActorID, v))
}

// ActorIDIn applies the In predicate on the "actor_id" field.
func ActorIDIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldActorID, vs...))
}

// ActorIDNotIn applies the NotIn predicate on the "actor_id" field.
func ActorIDNotIn(vs ...int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldActorID, vs...))
}

// ActorIDGT applies the GT predicate on the "actor_id" field.
func ActorIDGT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldActorID, v))
}

// ActorIDGTE applies the GTE predicate on the "actor_id" field.
func ActorIDGTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldActorID, v))
}

// ActorIDLT applies the LT predicate on the "actor_id" field.
func ActorIDLT(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldActorID, v))
}

// ActorIDLTE applies the LTE predicate on the "actor_id" field.
func ActorIDLTE(v int64) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldActorID, v))
}

// ActorIDIsNil applies the IsNil predicate on the "actor_id" field.
func ActorIDIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldActorID))
}

// ActorIDNotNil applies the NotNil predicate on the "actor_id" field.
func ActorIDNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldActorID))
}

// ActorNameEQ applies the EQ predicate on the "actor_name" field.
func ActorNameEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldActorName, v))
}

// ActorNameNEQ applies the NEQ predicate on the "actor_name" field.
func ActorNameNEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldActorName, v))
}

// ActorNameIn applies the In predicate on the "actor_name" field.
func ActorNameIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldActorName, vs...))
}

// ActorNameNotIn applies the NotIn predicate on the "actor_name" field.
func ActorNameNotIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldActorName, vs...))
}

// ActorNameGT applies the GT predicate on the "actor_name" field.
func ActorNameGT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldActorName, v))
}

// ActorNameGTE applies the GTE predicate on the "actor_name" field.
func ActorNameGTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldActorName, v))
}

// ActorNameLT applies the LT predicate on the "actor_name" field.
func ActorNameLT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldActorName, v))
}

// ActorNameLTE applies the LTE predicate on the "actor_name" field.
func ActorNameLTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldActorName, v))
}

// ActorNameContains applies the Contains predicate on the "actor_name" field.
func ActorNameContains(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContains(FieldActorName, v))
}

// ActorNameHasPrefix applies the HasPrefix predicate on the "actor_name" field.
func ActorNameHasPrefix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasPrefix(FieldActorName, v))
}

// ActorNameHasSuffix applies the HasSuffix predicate on the "actor_name" field.
func ActorNameHasSuffix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasSuffix(FieldActorName, v))
}

// ActorNameIsNil applies the IsNil predicate on the "actor_name" field.
func ActorNameIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldActorName))
}

// ActorNameNotNil applies the NotNil predicate on the "actor_name" field.
func ActorNameNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldActorName))
}

// ActorNameEqualFold applies the EqualFold predicate on the "actor_name" field.
func ActorNameEqualFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEqualFold(FieldActorName, v))
}

// ActorNameContainsFold applies the ContainsFold predicate on the "actor_name" field.
func ActorNameContainsFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContainsFold(FieldActorName, v))
}

// BeforeStateIsNil applies the IsNil predicate on the "before_state" field.
func BeforeStateIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldBeforeState))
}

// BeforeStateNotNil applies the NotNil predicate on the "before_state" field.
func BeforeStateNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldBeforeState))
}

// AfterStateIsNil applies the IsNil predicate on the "after_state" field.
func AfterStateIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldAfterState))
}

// AfterStateNotNil applies the NotNil predicate on the "after_state" field.
func AfterStateNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldAfterState))
}

// RequestIDEQ applies the EQ predicate on the "request_id" field.
func RequestIDEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldRequestID, v))
}

// RequestIDNEQ applies the NEQ predicate on the "request_id" field.
func RequestIDNEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldRequestID, v))
}

// RequestIDIn applies the In predicate on the "request_id" field.
func RequestIDIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldRequestID, vs...))
}

// RequestIDNotIn applies the NotIn predicate on the "request_id" field.
func RequestIDNotIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldRequestID, vs...))
}

// RequestIDGT applies the GT predicate on the "request_id" field.
func RequestIDGT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldRequestID, v))
}

// RequestIDGTE applies the GTE predicate on the "request_id" field.
func RequestIDGTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldRequestID, v))
}

// RequestIDLT applies the LT predicate on the "request_id" field.
func RequestIDLT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldRequestID, v))
}

// RequestIDLTE applies the LTE predicate on the "request_id" field.
func RequestIDLTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldRequestID, v))
}

// RequestIDContains applies the Contains predicate on the "request_id" field.
func RequestIDContains(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContains(FieldRequestID, v))
}

// RequestIDHasPrefix applies the HasPrefix predicate on the "request_id" field.
func RequestIDHasPrefix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasPrefix(FieldRequestID, v))
}

// RequestIDHasSuffix applies the HasSuffix predicate on the "request_id" field.
func RequestIDHasSuffix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasSuffix(FieldRequestID, v))
}

// RequestIDIsNil applies the IsNil predicate on the "request_id" field.
func RequestIDIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldRequestID))
}

// RequestIDNotNil applies the NotNil predicate on the "request_id" field.
func RequestIDNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldRequestID))
}

// RequestIDEqualFold applies the EqualFold predicate on the "request_id" field.
func RequestIDEqualFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEqualFold(FieldRequestID, v))
}

// RequestIDContainsFold applies the ContainsFold predicate on the "request_id" field.
func RequestIDContainsFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContainsFold(FieldRequestID, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldHasSuffix(FieldNote, v))
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldIsNull(FieldNote))
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldNotNull(FieldNote))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.FieldContainsFold(FieldNote, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromptAdminEvent) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromptAdminEvent) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromptAdminEvent) predicate.PromptAdminEvent {
	return predicate.PromptAdminEvent(sql.NotPredicates(p))
}
