// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountgrouppromptoverride"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountGroupPromptOverrideDelete is the builder for deleting a AccountGroupPromptOverride entity.
type AccountGroupPromptOverrideDelete struct {
	config
	hooks    []Hook
	mutation *AccountGroupPromptOverrideMutation
}

// Where appends a list predicates to the AccountGroupPromptOverrideDelete builder.
func (_d *AccountGroupPromptOverrideDelete) Where(ps ...predicate.AccountGroupPromptOverride) *AccountGroupPromptOverrideDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountGroupPromptOverrideDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountGroupPromptOverrideDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountGroupPromptOverrideDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountgrouppromptoverride.Table, sqlgraph.NewFieldSpec(accountgrouppromptoverride.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountGroupPromptOverrideDeleteOne is the builder for deleting a single AccountGroupPromptOverride entity.
type AccountGroupPromptOverrideDeleteOne struct {
	_d *AccountGroupPromptOverrideDelete
}

// Where appends a list predicates to the AccountGroupPromptOverrideDelete builder.
func (_d *AccountGroupPromptOverrideDeleteOne) Where(ps ...predicate.AccountGroupPromptOverride) *AccountGroupPromptOverrideDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountGroupPromptOverrideDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountgrouppromptoverride.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountGroupPromptOverrideDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
