// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountgrouppromptoverride"
)

// AccountGroupPromptOverrideCreate is the builder for creating a AccountGroupPromptOverride entity.
type AccountGroupPromptOverrideCreate struct {
	config
	mutation *AccountGroupPromptOverrideMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountGroupPromptOverrideCreate) SetCreatedAt(v time.Time) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountGroupPromptOverrideCreate) SetNillableCreatedAt(v *time.Time) *AccountGroupPromptOverrideCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountGroupPromptOverrideCreate) SetUpdatedAt(v time.Time) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountGroupPromptOverrideCreate) SetNillableUpdatedAt(v *time.Time) *AccountGroupPromptOverrideCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountGroupPromptOverrideCreate) SetAccountID(v int64) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *AccountGroupPromptOverrideCreate) SetGroupID(v int64) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetMode sets the "mode" field.
func (_c *AccountGroupPromptOverrideCreate) SetMode(v string) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetMode(v)
	return _c
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_c *AccountGroupPromptOverrideCreate) SetNillableMode(v *string) *AccountGroupPromptOverrideCreate {
	if v != nil {
		_c.SetMode(*v)
	}
	return _c
}

// SetVersionID sets the "version_id" field.
func (_c *AccountGroupPromptOverrideCreate) SetVersionID(v int64) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetVersionID(v)
	return _c
}

// SetNillableVersionID sets the "version_id" field if the given value is not nil.
func (_c *AccountGroupPromptOverrideCreate) SetNillableVersionID(v *int64) *AccountGroupPromptOverrideCreate {
	if v != nil {
		_c.SetVersionID(*v)
	}
	return _c
}

// SetRevision sets the "revision" field.
func (_c *AccountGroupPromptOverrideCreate) SetRevision(v int) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *AccountGroupPromptOverrideCreate) SetNillableRevision(v *int) *AccountGroupPromptOverrideCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *AccountGroupPromptOverrideCreate) SetUpdatedBy(v int64) *AccountGroupPromptOverrideCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *AccountGroupPromptOverrideCreate) SetNillableUpdatedBy(v *int64) *AccountGroupPromptOverrideCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// Mutation returns the AccountGroupPromptOverrideMutation object of the builder.
func (_c *AccountGroupPromptOverrideCreate) Mutation() *AccountGroupPromptOverrideMutation {
	return _c.mutation
}

// Save creates the AccountGroupPromptOverride in the database.
func (_c *AccountGroupPromptOverrideCreate) Save(ctx context.Context) (*AccountGroupPromptOverride, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountGroupPromptOverrideCreate) SaveX(ctx context.Context) *AccountGroupPromptOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountGroupPromptOverrideCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountGroupPromptOverrideCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountGroupPromptOverrideCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountgrouppromptoverride.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountgrouppromptoverride.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Mode(); !ok {
		v := accountgrouppromptoverride.DefaultMode
		_c.mutation.SetMode(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := accountgrouppromptoverride.DefaultRevision
		_c.mutation.SetRevision(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountGroupPromptOverrideCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountGroupPromptOverride.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountGroupPromptOverride.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountGroupPromptOverride.account_id"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "AccountGroupPromptOverride.group_id"`)}
	}
	if _, ok := _c.mutation.Mode(); !ok {
		return &ValidationError{Name: "mode", err: errors.New(`ent: missing required field "AccountGroupPromptOverride.mode"`)}
	}
	if v, ok := _c.mutation.Mode(); ok {
		if err := accountgrouppromptoverride.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "AccountGroupPromptOverride.mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "AccountGroupPromptOverride.revision"`)}
	}
	return nil
}

func (_c *AccountGroupPromptOverrideCreate) sqlSave(ctx context.Context) (*AccountGroupPromptOverride, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountGroupPromptOverrideCreate) createSpec() (*AccountGroupPromptOverride, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountGroupPromptOverride{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountgrouppromptoverride.Table, sqlgraph.NewFieldSpec(accountgrouppromptoverride.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = value
	}
	if value, ok := _c.mutation.Mode(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldMode, field.TypeString, value)
		_node.Mode = value
	}
	if value, ok := _c.mutation.VersionID(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldVersionID, field.TypeInt64, value)
		_node.VersionID = &value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(accountgrouppromptoverride.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountGroupPromptOverride.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountGroupPromptOverrideUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountGroupPromptOverrideCreate) OnConflict(opts ...sql.ConflictOption) *AccountGroupPromptOverrideUpsertOne {
	_c.conflict = opts
	return &AccountGroupPromptOverrideUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountGroupPromptOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountGroupPromptOverrideCreate) OnConflictColumns(columns ...string) *AccountGroupPromptOverrideUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountGroupPromptOverrideUpsertOne{
		create: _c,
	}
}

type (
	// AccountGroupPromptOverrideUpsertOne is the builder for "upsert"-ing
	//  one AccountGroupPromptOverride node.
	AccountGroupPromptOverrideUpsertOne struct {
		create *AccountGroupPromptOverrideCreate
	}

	// AccountGroupPromptOverrideUpsert is the "OnConflict" setter.
	AccountGroupPromptOverrideUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountGroupPromptOverrideUpsert) SetUpdatedAt(v time.Time) *AccountGroupPromptOverrideUpsert {
	u.Set(accountgrouppromptoverride.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsert) UpdateUpdatedAt() *AccountGroupPromptOverrideUpsert {
	u.SetExcluded(accountgrouppromptoverride.FieldUpdatedAt)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *AccountGroupPromptOverrideUpsert) SetAccountID(v int64) *AccountGroupPromptOverrideUpsert {
	u.Set(accountgrouppromptoverride.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsert) UpdateAccountID() *AccountGroupPromptOverrideUpsert {
	u.SetExcluded(accountgrouppromptoverride.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountGroupPromptOverrideUpsert) AddAccountID(v int64) *AccountGroupPromptOverrideUpsert {
	u.Add(accountgrouppromptoverride.FieldAccountID, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *AccountGroupPromptOverrideUpsert) SetGroupID(v int64) *AccountGroupPromptOverrideUpsert {
	u.Set(accountgrouppromptoverride.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsert) UpdateGroupID() *AccountGroupPromptOverrideUpsert {
	u.SetExcluded(accountgrouppromptoverride.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *AccountGroupPromptOverrideUpsert) AddGroupID(v int64) *AccountGroupPromptOverrideUpsert {
	u.Add(accountgrouppromptoverride.FieldGroupID, v)
	return u
}

// SetMode sets the "mode" field.
func (u *AccountGroupPromptOverrideUpsert) SetMode(v string) *AccountGroupPromptOverrideUpsert {
	u.Set(accountgrouppromptoverride.FieldMode, v)
	return u
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsert) UpdateMode() *AccountGroupPromptOverrideUpsert {
	u.SetExcluded(accountgrouppromptoverride.FieldMode)
	return u
}

// SetVersionID sets the "version_id" field.
func (u *AccountGroupPromptOverrideUpsert) SetVersionID(v int64) *AccountGroupPromptOverrideUpsert {
	u.Set(accountgrouppromptoverride.FieldVersionID, v)
	return u
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsert) UpdateVersionID() *AccountGroupPromptOverrideUpsert {
	u.SetExcluded(accountgrouppromptoverride.FieldVersionID)
	return u
}

// AddVersionID adds v to the "version_id" field.
func (u *AccountGroupPromptOverrideUpsert) AddVersionID(v int64) *AccountGroupPromptOverrideUpsert {
	u.Add(accountgrouppromptoverride.FieldVersionID, v)
	return u
}

// ClearVersionID clears the value of the "version_id" field.
func (u *AccountGroupPromptOverrideUpsert) ClearVersionID() *AccountGroupPromptOverrideUpsert {
	u.SetNull(accountgrouppromptoverride.FieldVersionID)
	return u
}

// SetRevision sets the "revision" field.
func (u *AccountGroupPromptOverrideUpsert) SetRevision(v int) *AccountGroupPromptOverrideUpsert {
	u.Set(accountgrouppromptoverride.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsert) UpdateRevision() *AccountGroupPromptOverrideUpsert {
	u.SetExcluded(accountgrouppromptoverride.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *AccountGroupPromptOverrideUpsert) AddRevision(v int) *AccountGroupPromptOverrideUpsert {
	u.Add(accountgrouppromptoverride.FieldRevision, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsert) SetUpdatedBy(v int64) *AccountGroupPromptOverrideUpsert {
	u.Set(accountgrouppromptoverride.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsert) UpdateUpdatedBy() *AccountGroupPromptOverrideUpsert {
	u.SetExcluded(accountgrouppromptoverride.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsert) AddUpdatedBy(v int64) *AccountGroupPromptOverrideUpsert {
	u.Add(accountgrouppromptoverride.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsert) ClearUpdatedBy() *AccountGroupPromptOverrideUpsert {
	u.SetNull(accountgrouppromptoverride.FieldUpdatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AccountGroupPromptOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountGroupPromptOverrideUpsertOne) UpdateNewValues() *AccountGroupPromptOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(accountgrouppromptoverride.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountGroupPromptOverride.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AccountGroupPromptOverrideUpsertOne) Ignore() *AccountGroupPromptOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountGroupPromptOverrideUpsertOne) DoNothing() *AccountGroupPromptOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountGroupPromptOverrideCreate.OnConflict
// documentation for more info.
func (u *AccountGroupPromptOverrideUpsertOne) Update(set func(*AccountGroupPromptOverrideUpsert)) *AccountGroupPromptOverrideUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountGroupPromptOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountGroupPromptOverrideUpsertOne) SetUpdatedAt(v time.Time) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertOne) UpdateUpdatedAt() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountGroupPromptOverrideUpsertOne) SetAccountID(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountGroupPromptOverrideUpsertOne) AddAccountID(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertOne) UpdateAccountID() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AccountGroupPromptOverrideUpsertOne) SetGroupID(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *AccountGroupPromptOverrideUpsertOne) AddGroupID(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertOne) UpdateGroupID() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateGroupID()
	})
}

// SetMode sets the "mode" field.
func (u *AccountGroupPromptOverrideUpsertOne) SetMode(v string) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertOne) UpdateMode() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateMode()
	})
}

// SetVersionID sets the "version_id" field.
func (u *AccountGroupPromptOverrideUpsertOne) SetVersionID(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetVersionID(v)
	})
}

// AddVersionID adds v to the "version_id" field.
func (u *AccountGroupPromptOverrideUpsertOne) AddVersionID(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddVersionID(v)
	})
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertOne) UpdateVersionID() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateVersionID()
	})
}

// ClearVersionID clears the value of the "version_id" field.
func (u *AccountGroupPromptOverrideUpsertOne) ClearVersionID() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.ClearVersionID()
	})
}

// SetRevision sets the "revision" field.
func (u *AccountGroupPromptOverrideUpsertOne) SetRevision(v int) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *AccountGroupPromptOverrideUpsertOne) AddRevision(v int) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertOne) UpdateRevision() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsertOne) SetUpdatedBy(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsertOne) AddUpdatedBy(v int64) *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertOne) UpdateUpdatedBy() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsertOne) ClearUpdatedBy() *AccountGroupPromptOverrideUpsertOne {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *AccountGroupPromptOverrideUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountGroupPromptOverrideCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountGroupPromptOverrideUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AccountGroupPromptOverrideUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AccountGroupPromptOverrideUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AccountGroupPromptOverrideCreateBulk is the builder for creating many AccountGroupPromptOverride entities in bulk.
type AccountGroupPromptOverrideCreateBulk struct {
	config
	err      error
	builders []*AccountGroupPromptOverrideCreate
	conflict []sql.ConflictOption
}

// Save creates the AccountGroupPromptOverride entities in the database.
func (_c *AccountGroupPromptOverrideCreateBulk) Save(ctx context.Context) ([]*AccountGroupPromptOverride, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountGroupPromptOverride, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountGroupPromptOverrideMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountGroupPromptOverrideCreateBulk) SaveX(ctx context.Context) []*AccountGroupPromptOverride {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountGroupPromptOverrideCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountGroupPromptOverrideCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AccountGroupPromptOverride.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AccountGroupPromptOverrideUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *AccountGroupPromptOverrideCreateBulk) OnConflict(opts ...sql.ConflictOption) *AccountGroupPromptOverrideUpsertBulk {
	_c.conflict = opts
	return &AccountGroupPromptOverrideUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AccountGroupPromptOverride.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AccountGroupPromptOverrideCreateBulk) OnConflictColumns(columns ...string) *AccountGroupPromptOverrideUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AccountGroupPromptOverrideUpsertBulk{
		create: _c,
	}
}

// AccountGroupPromptOverrideUpsertBulk is the builder for "upsert"-ing
// a bulk of AccountGroupPromptOverride nodes.
type AccountGroupPromptOverrideUpsertBulk struct {
	create *AccountGroupPromptOverrideCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AccountGroupPromptOverride.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateNewValues() *AccountGroupPromptOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(accountgrouppromptoverride.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AccountGroupPromptOverride.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AccountGroupPromptOverrideUpsertBulk) Ignore() *AccountGroupPromptOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AccountGroupPromptOverrideUpsertBulk) DoNothing() *AccountGroupPromptOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AccountGroupPromptOverrideCreateBulk.OnConflict
// documentation for more info.
func (u *AccountGroupPromptOverrideUpsertBulk) Update(set func(*AccountGroupPromptOverrideUpsert)) *AccountGroupPromptOverrideUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AccountGroupPromptOverrideUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AccountGroupPromptOverrideUpsertBulk) SetUpdatedAt(v time.Time) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateUpdatedAt() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetAccountID sets the "account_id" field.
func (u *AccountGroupPromptOverrideUpsertBulk) SetAccountID(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *AccountGroupPromptOverrideUpsertBulk) AddAccountID(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateAccountID() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateAccountID()
	})
}

// SetGroupID sets the "group_id" field.
func (u *AccountGroupPromptOverrideUpsertBulk) SetGroupID(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *AccountGroupPromptOverrideUpsertBulk) AddGroupID(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateGroupID() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateGroupID()
	})
}

// SetMode sets the "mode" field.
func (u *AccountGroupPromptOverrideUpsertBulk) SetMode(v string) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetMode(v)
	})
}

// UpdateMode sets the "mode" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateMode() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateMode()
	})
}

// SetVersionID sets the "version_id" field.
func (u *AccountGroupPromptOverrideUpsertBulk) SetVersionID(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetVersionID(v)
	})
}

// AddVersionID adds v to the "version_id" field.
func (u *AccountGroupPromptOverrideUpsertBulk) AddVersionID(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddVersionID(v)
	})
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateVersionID() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateVersionID()
	})
}

// ClearVersionID clears the value of the "version_id" field.
func (u *AccountGroupPromptOverrideUpsertBulk) ClearVersionID() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.ClearVersionID()
	})
}

// SetRevision sets the "revision" field.
func (u *AccountGroupPromptOverrideUpsertBulk) SetRevision(v int) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *AccountGroupPromptOverrideUpsertBulk) AddRevision(v int) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateRevision() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsertBulk) SetUpdatedBy(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsertBulk) AddUpdatedBy(v int64) *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *AccountGroupPromptOverrideUpsertBulk) UpdateUpdatedBy() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *AccountGroupPromptOverrideUpsertBulk) ClearUpdatedBy() *AccountGroupPromptOverrideUpsertBulk {
	return u.Update(func(s *AccountGroupPromptOverrideUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *AccountGroupPromptOverrideUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AccountGroupPromptOverrideCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AccountGroupPromptOverrideCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AccountGroupPromptOverrideUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
