// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/prompttemplateversion"
)

// PromptTemplateVersionCreate is the builder for creating a PromptTemplateVersion entity.
type PromptTemplateVersionCreate struct {
	config
	mutation *PromptTemplateVersionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptTemplateVersionCreate) SetCreatedAt(v time.Time) *PromptTemplateVersionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptTemplateVersionCreate) SetNillableCreatedAt(v *time.Time) *PromptTemplateVersionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromptTemplateVersionCreate) SetUpdatedAt(v time.Time) *PromptTemplateVersionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromptTemplateVersionCreate) SetNillableUpdatedAt(v *time.Time) *PromptTemplateVersionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *PromptTemplateVersionCreate) SetTemplateID(v int64) *PromptTemplateVersionCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetVersionNo sets the "version_no" field.
func (_c *PromptTemplateVersionCreate) SetVersionNo(v int) *PromptTemplateVersionCreate {
	_c.mutation.SetVersionNo(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *PromptTemplateVersionCreate) SetBody(v string) *PromptTemplateVersionCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetBodySha256 sets the "body_sha256" field.
func (_c *PromptTemplateVersionCreate) SetBodySha256(v string) *PromptTemplateVersionCreate {
	_c.mutation.SetBodySha256(v)
	return _c
}

// SetBodyBytes sets the "body_bytes" field.
func (_c *PromptTemplateVersionCreate) SetBodyBytes(v int) *PromptTemplateVersionCreate {
	_c.mutation.SetBodyBytes(v)
	return _c
}

// SetClientModels sets the "client_models" field.
func (_c *PromptTemplateVersionCreate) SetClientModels(v []string) *PromptTemplateVersionCreate {
	_c.mutation.SetClientModels(v)
	return _c
}

// SetUpstreamModels sets the "upstream_models" field.
func (_c *PromptTemplateVersionCreate) SetUpstreamModels(v []string) *PromptTemplateVersionCreate {
	_c.mutation.SetUpstreamModels(v)
	return _c
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (_c *PromptTemplateVersionCreate) SetSupportedProfiles(v []string) *PromptTemplateVersionCreate {
	_c.mutation.SetSupportedProfiles(v)
	return _c
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (_c *PromptTemplateVersionCreate) SetManifestSha256(v string) *PromptTemplateVersionCreate {
	_c.mutation.SetManifestSha256(v)
	return _c
}

// SetChangeNote sets the "change_note" field.
func (_c *PromptTemplateVersionCreate) SetChangeNote(v string) *PromptTemplateVersionCreate {
	_c.mutation.SetChangeNote(v)
	return _c
}

// SetNillableChangeNote sets the "change_note" field if the given value is not nil.
func (_c *PromptTemplateVersionCreate) SetNillableChangeNote(v *string) *PromptTemplateVersionCreate {
	if v != nil {
		_c.SetChangeNote(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *PromptTemplateVersionCreate) SetIdempotencyKey(v string) *PromptTemplateVersionCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_c *PromptTemplateVersionCreate) SetNillableIdempotencyKey(v *string) *PromptTemplateVersionCreate {
	if v != nil {
		_c.SetIdempotencyKey(*v)
	}
	return _c
}

// SetPublishedBy sets the "published_by" field.
func (_c *PromptTemplateVersionCreate) SetPublishedBy(v int64) *PromptTemplateVersionCreate {
	_c.mutation.SetPublishedBy(v)
	return _c
}

// SetNillablePublishedBy sets the "published_by" field if the given value is not nil.
func (_c *PromptTemplateVersionCreate) SetNillablePublishedBy(v *int64) *PromptTemplateVersionCreate {
	if v != nil {
		_c.SetPublishedBy(*v)
	}
	return _c
}

// SetPublishedAt sets the "published_at" field.
func (_c *PromptTemplateVersionCreate) SetPublishedAt(v time.Time) *PromptTemplateVersionCreate {
	_c.mutation.SetPublishedAt(v)
	return _c
}

// Mutation returns the PromptTemplateVersionMutation object of the builder.
func (_c *PromptTemplateVersionCreate) Mutation() *PromptTemplateVersionMutation {
	return _c.mutation
}

// Save creates the PromptTemplateVersion in the database.
func (_c *PromptTemplateVersionCreate) Save(ctx context.Context) (*PromptTemplateVersion, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptTemplateVersionCreate) SaveX(ctx context.Context) *PromptTemplateVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateVersionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateVersionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptTemplateVersionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := prompttemplateversion.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := prompttemplateversion.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ClientModels(); !ok {
		v := prompttemplateversion.DefaultClientModels()
		_c.mutation.SetClientModels(v)
	}
	if _, ok := _c.mutation.UpstreamModels(); !ok {
		v := prompttemplateversion.DefaultUpstreamModels()
		_c.mutation.SetUpstreamModels(v)
	}
	if _, ok := _c.mutation.SupportedProfiles(); !ok {
		v := prompttemplateversion.DefaultSupportedProfiles()
		_c.mutation.SetSupportedProfiles(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptTemplateVersionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromptTemplateVersion.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromptTemplateVersion.updated_at"`)}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "PromptTemplateVersion.template_id"`)}
	}
	if _, ok := _c.mutation.VersionNo(); !ok {
		return &ValidationError{Name: "version_no", err: errors.New(`ent: missing required field "PromptTemplateVersion.version_no"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "PromptTemplateVersion.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := prompttemplateversion.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BodySha256(); !ok {
		return &ValidationError{Name: "body_sha256", err: errors.New(`ent: missing required field "PromptTemplateVersion.body_sha256"`)}
	}
	if v, ok := _c.mutation.BodySha256(); ok {
		if err := prompttemplateversion.BodySha256Validator(v); err != nil {
			return &ValidationError{Name: "body_sha256", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.body_sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BodyBytes(); !ok {
		return &ValidationError{Name: "body_bytes", err: errors.New(`ent: missing required field "PromptTemplateVersion.body_bytes"`)}
	}
	if _, ok := _c.mutation.ClientModels(); !ok {
		return &ValidationError{Name: "client_models", err: errors.New(`ent: missing required field "PromptTemplateVersion.client_models"`)}
	}
	if _, ok := _c.mutation.UpstreamModels(); !ok {
		return &ValidationError{Name: "upstream_models", err: errors.New(`ent: missing required field "PromptTemplateVersion.upstream_models"`)}
	}
	if _, ok := _c.mutation.SupportedProfiles(); !ok {
		return &ValidationError{Name: "supported_profiles", err: errors.New(`ent: missing required field "PromptTemplateVersion.supported_profiles"`)}
	}
	if _, ok := _c.mutation.ManifestSha256(); !ok {
		return &ValidationError{Name: "manifest_sha256", err: errors.New(`ent: missing required field "PromptTemplateVersion.manifest_sha256"`)}
	}
	if v, ok := _c.mutation.ManifestSha256(); ok {
		if err := prompttemplateversion.ManifestSha256Validator(v); err != nil {
			return &ValidationError{Name: "manifest_sha256", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.manifest_sha256": %w`, err)}
		}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := prompttemplateversion.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PublishedAt(); !ok {
		return &ValidationError{Name: "published_at", err: errors.New(`ent: missing required field "PromptTemplateVersion.published_at"`)}
	}
	return nil
}

func (_c *PromptTemplateVersionCreate) sqlSave(ctx context.Context) (*PromptTemplateVersion, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptTemplateVersionCreate) createSpec() (*PromptTemplateVersion, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptTemplateVersion{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(prompttemplateversion.Table, sqlgraph.NewFieldSpec(prompttemplateversion.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(prompttemplateversion.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplateversion.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(prompttemplateversion.FieldTemplateID, field.TypeInt64, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.VersionNo(); ok {
		_spec.SetField(prompttemplateversion.FieldVersionNo, field.TypeInt, value)
		_node.VersionNo = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(prompttemplateversion.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.BodySha256(); ok {
		_spec.SetField(prompttemplateversion.FieldBodySha256, field.TypeString, value)
		_node.BodySha256 = value
	}
	if value, ok := _c.mutation.BodyBytes(); ok {
		_spec.SetField(prompttemplateversion.FieldBodyBytes, field.TypeInt, value)
		_node.BodyBytes = value
	}
	if value, ok := _c.mutation.ClientModels(); ok {
		_spec.SetField(prompttemplateversion.FieldClientModels, field.TypeJSON, value)
		_node.ClientModels = value
	}
	if value, ok := _c.mutation.UpstreamModels(); ok {
		_spec.SetField(prompttemplateversion.FieldUpstreamModels, field.TypeJSON, value)
		_node.UpstreamModels = value
	}
	if value, ok := _c.mutation.SupportedProfiles(); ok {
		_spec.SetField(prompttemplateversion.FieldSupportedProfiles, field.TypeJSON, value)
		_node.SupportedProfiles = value
	}
	if value, ok := _c.mutation.ManifestSha256(); ok {
		_spec.SetField(prompttemplateversion.FieldManifestSha256, field.TypeString, value)
		_node.ManifestSha256 = value
	}
	if value, ok := _c.mutation.ChangeNote(); ok {
		_spec.SetField(prompttemplateversion.FieldChangeNote, field.TypeString, value)
		_node.ChangeNote = &value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(prompttemplateversion.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = &value
	}
	if value, ok := _c.mutation.PublishedBy(); ok {
		_spec.SetField(prompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
		_node.PublishedBy = &value
	}
	if value, ok := _c.mutation.PublishedAt(); ok {
		_spec.SetField(prompttemplateversion.FieldPublishedAt, field.TypeTime, value)
		_node.PublishedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptTemplateVersion.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptTemplateVersionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptTemplateVersionCreate) OnConflict(opts ...sql.ConflictOption) *PromptTemplateVersionUpsertOne {
	_c.conflict = opts
	return &PromptTemplateVersionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptTemplateVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptTemplateVersionCreate) OnConflictColumns(columns ...string) *PromptTemplateVersionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptTemplateVersionUpsertOne{
		create: _c,
	}
}

type (
	// PromptTemplateVersionUpsertOne is the builder for "upsert"-ing
	//  one PromptTemplateVersion node.
	PromptTemplateVersionUpsertOne struct {
		create *PromptTemplateVersionCreate
	}

	// PromptTemplateVersionUpsert is the "OnConflict" setter.
	PromptTemplateVersionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptTemplateVersionUpsert) SetUpdatedAt(v time.Time) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateUpdatedAt() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldUpdatedAt)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *PromptTemplateVersionUpsert) SetTemplateID(v int64) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateTemplateID() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldTemplateID)
	return u
}

// AddTemplateID adds v to the "template_id" field.
func (u *PromptTemplateVersionUpsert) AddTemplateID(v int64) *PromptTemplateVersionUpsert {
	u.Add(prompttemplateversion.FieldTemplateID, v)
	return u
}

// SetVersionNo sets the "version_no" field.
func (u *PromptTemplateVersionUpsert) SetVersionNo(v int) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldVersionNo, v)
	return u
}

// UpdateVersionNo sets the "version_no" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateVersionNo() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldVersionNo)
	return u
}

// AddVersionNo adds v to the "version_no" field.
func (u *PromptTemplateVersionUpsert) AddVersionNo(v int) *PromptTemplateVersionUpsert {
	u.Add(prompttemplateversion.FieldVersionNo, v)
	return u
}

// SetBody sets the "body" field.
func (u *PromptTemplateVersionUpsert) SetBody(v string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateBody() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldBody)
	return u
}

// SetBodySha256 sets the "body_sha256" field.
func (u *PromptTemplateVersionUpsert) SetBodySha256(v string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldBodySha256, v)
	return u
}

// UpdateBodySha256 sets the "body_sha256" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateBodySha256() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldBodySha256)
	return u
}

// SetBodyBytes sets the "body_bytes" field.
func (u *PromptTemplateVersionUpsert) SetBodyBytes(v int) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldBodyBytes, v)
	return u
}

// UpdateBodyBytes sets the "body_bytes" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateBodyBytes() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldBodyBytes)
	return u
}

// AddBodyBytes adds v to the "body_bytes" field.
func (u *PromptTemplateVersionUpsert) AddBodyBytes(v int) *PromptTemplateVersionUpsert {
	u.Add(prompttemplateversion.FieldBodyBytes, v)
	return u
}

// SetClientModels sets the "client_models" field.
func (u *PromptTemplateVersionUpsert) SetClientModels(v []string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldClientModels, v)
	return u
}

// UpdateClientModels sets the "client_models" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateClientModels() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldClientModels)
	return u
}

// SetUpstreamModels sets the "upstream_models" field.
func (u *PromptTemplateVersionUpsert) SetUpstreamModels(v []string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldUpstreamModels, v)
	return u
}

// UpdateUpstreamModels sets the "upstream_models" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateUpstreamModels() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldUpstreamModels)
	return u
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (u *PromptTemplateVersionUpsert) SetSupportedProfiles(v []string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldSupportedProfiles, v)
	return u
}

// UpdateSupportedProfiles sets the "supported_profiles" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateSupportedProfiles() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldSupportedProfiles)
	return u
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (u *PromptTemplateVersionUpsert) SetManifestSha256(v string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldManifestSha256, v)
	return u
}

// UpdateManifestSha256 sets the "manifest_sha256" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateManifestSha256() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldManifestSha256)
	return u
}

// SetChangeNote sets the "change_note" field.
func (u *PromptTemplateVersionUpsert) SetChangeNote(v string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldChangeNote, v)
	return u
}

// UpdateChangeNote sets the "change_note" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateChangeNote() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldChangeNote)
	return u
}

// ClearChangeNote clears the value of the "change_note" field.
func (u *PromptTemplateVersionUpsert) ClearChangeNote() *PromptTemplateVersionUpsert {
	u.SetNull(prompttemplateversion.FieldChangeNote)
	return u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *PromptTemplateVersionUpsert) SetIdempotencyKey(v string) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldIdempotencyKey, v)
	return u
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdateIdempotencyKey() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldIdempotencyKey)
	return u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *PromptTemplateVersionUpsert) ClearIdempotencyKey() *PromptTemplateVersionUpsert {
	u.SetNull(prompttemplateversion.FieldIdempotencyKey)
	return u
}

// SetPublishedBy sets the "published_by" field.
func (u *PromptTemplateVersionUpsert) SetPublishedBy(v int64) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldPublishedBy, v)
	return u
}

// UpdatePublishedBy sets the "published_by" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdatePublishedBy() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldPublishedBy)
	return u
}

// AddPublishedBy adds v to the "published_by" field.
func (u *PromptTemplateVersionUpsert) AddPublishedBy(v int64) *PromptTemplateVersionUpsert {
	u.Add(prompttemplateversion.FieldPublishedBy, v)
	return u
}

// ClearPublishedBy clears the value of the "published_by" field.
func (u *PromptTemplateVersionUpsert) ClearPublishedBy() *PromptTemplateVersionUpsert {
	u.SetNull(prompttemplateversion.FieldPublishedBy)
	return u
}

// SetPublishedAt sets the "published_at" field.
func (u *PromptTemplateVersionUpsert) SetPublishedAt(v time.Time) *PromptTemplateVersionUpsert {
	u.Set(prompttemplateversion.FieldPublishedAt, v)
	return u
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsert) UpdatePublishedAt() *PromptTemplateVersionUpsert {
	u.SetExcluded(prompttemplateversion.FieldPublishedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromptTemplateVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptTemplateVersionUpsertOne) UpdateNewValues() *PromptTemplateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(prompttemplateversion.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptTemplateVersion.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromptTemplateVersionUpsertOne) Ignore() *PromptTemplateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptTemplateVersionUpsertOne) DoNothing() *PromptTemplateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptTemplateVersionCreate.OnConflict
// documentation for more info.
func (u *PromptTemplateVersionUpsertOne) Update(set func(*PromptTemplateVersionUpsert)) *PromptTemplateVersionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptTemplateVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptTemplateVersionUpsertOne) SetUpdatedAt(v time.Time) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateUpdatedAt() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *PromptTemplateVersionUpsertOne) SetTemplateID(v int64) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *PromptTemplateVersionUpsertOne) AddTemplateID(v int64) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateTemplateID() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateTemplateID()
	})
}

// SetVersionNo sets the "version_no" field.
func (u *PromptTemplateVersionUpsertOne) SetVersionNo(v int) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetVersionNo(v)
	})
}

// AddVersionNo adds v to the "version_no" field.
func (u *PromptTemplateVersionUpsertOne) AddVersionNo(v int) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddVersionNo(v)
	})
}

// UpdateVersionNo sets the "version_no" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateVersionNo() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateVersionNo()
	})
}

// SetBody sets the "body" field.
func (u *PromptTemplateVersionUpsertOne) SetBody(v string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateBody() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateBody()
	})
}

// SetBodySha256 sets the "body_sha256" field.
func (u *PromptTemplateVersionUpsertOne) SetBodySha256(v string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetBodySha256(v)
	})
}

// UpdateBodySha256 sets the "body_sha256" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateBodySha256() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateBodySha256()
	})
}

// SetBodyBytes sets the "body_bytes" field.
func (u *PromptTemplateVersionUpsertOne) SetBodyBytes(v int) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetBodyBytes(v)
	})
}

// AddBodyBytes adds v to the "body_bytes" field.
func (u *PromptTemplateVersionUpsertOne) AddBodyBytes(v int) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddBodyBytes(v)
	})
}

// UpdateBodyBytes sets the "body_bytes" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateBodyBytes() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateBodyBytes()
	})
}

// SetClientModels sets the "client_models" field.
func (u *PromptTemplateVersionUpsertOne) SetClientModels(v []string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetClientModels(v)
	})
}

// UpdateClientModels sets the "client_models" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateClientModels() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateClientModels()
	})
}

// SetUpstreamModels sets the "upstream_models" field.
func (u *PromptTemplateVersionUpsertOne) SetUpstreamModels(v []string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetUpstreamModels(v)
	})
}

// UpdateUpstreamModels sets the "upstream_models" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateUpstreamModels() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateUpstreamModels()
	})
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (u *PromptTemplateVersionUpsertOne) SetSupportedProfiles(v []string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetSupportedProfiles(v)
	})
}

// UpdateSupportedProfiles sets the "supported_profiles" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateSupportedProfiles() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateSupportedProfiles()
	})
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (u *PromptTemplateVersionUpsertOne) SetManifestSha256(v string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetManifestSha256(v)
	})
}

// UpdateManifestSha256 sets the "manifest_sha256" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateManifestSha256() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateManifestSha256()
	})
}

// SetChangeNote sets the "change_note" field.
func (u *PromptTemplateVersionUpsertOne) SetChangeNote(v string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetChangeNote(v)
	})
}

// UpdateChangeNote sets the "change_note" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateChangeNote() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateChangeNote()
	})
}

// ClearChangeNote clears the value of the "change_note" field.
func (u *PromptTemplateVersionUpsertOne) ClearChangeNote() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.ClearChangeNote()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *PromptTemplateVersionUpsertOne) SetIdempotencyKey(v string) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdateIdempotencyKey() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *PromptTemplateVersionUpsertOne) ClearIdempotencyKey() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetPublishedBy sets the "published_by" field.
func (u *PromptTemplateVersionUpsertOne) SetPublishedBy(v int64) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetPublishedBy(v)
	})
}

// AddPublishedBy adds v to the "published_by" field.
func (u *PromptTemplateVersionUpsertOne) AddPublishedBy(v int64) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddPublishedBy(v)
	})
}

// UpdatePublishedBy sets the "published_by" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdatePublishedBy() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdatePublishedBy()
	})
}

// ClearPublishedBy clears the value of the "published_by" field.
func (u *PromptTemplateVersionUpsertOne) ClearPublishedBy() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.ClearPublishedBy()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *PromptTemplateVersionUpsertOne) SetPublishedAt(v time.Time) *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertOne) UpdatePublishedAt() *PromptTemplateVersionUpsertOne {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdatePublishedAt()
	})
}

// Exec executes the query.
func (u *PromptTemplateVersionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptTemplateVersionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptTemplateVersionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromptTemplateVersionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromptTemplateVersionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromptTemplateVersionCreateBulk is the builder for creating many PromptTemplateVersion entities in bulk.
type PromptTemplateVersionCreateBulk struct {
	config
	err      error
	builders []*PromptTemplateVersionCreate
	conflict []sql.ConflictOption
}

// Save creates the PromptTemplateVersion entities in the database.
func (_c *PromptTemplateVersionCreateBulk) Save(ctx context.Context) ([]*PromptTemplateVersion, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptTemplateVersion, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptTemplateVersionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptTemplateVersionCreateBulk) SaveX(ctx context.Context) []*PromptTemplateVersion {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateVersionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateVersionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptTemplateVersion.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptTemplateVersionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptTemplateVersionCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromptTemplateVersionUpsertBulk {
	_c.conflict = opts
	return &PromptTemplateVersionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptTemplateVersion.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptTemplateVersionCreateBulk) OnConflictColumns(columns ...string) *PromptTemplateVersionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptTemplateVersionUpsertBulk{
		create: _c,
	}
}

// PromptTemplateVersionUpsertBulk is the builder for "upsert"-ing
// a bulk of PromptTemplateVersion nodes.
type PromptTemplateVersionUpsertBulk struct {
	create *PromptTemplateVersionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromptTemplateVersion.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptTemplateVersionUpsertBulk) UpdateNewValues() *PromptTemplateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(prompttemplateversion.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptTemplateVersion.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromptTemplateVersionUpsertBulk) Ignore() *PromptTemplateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptTemplateVersionUpsertBulk) DoNothing() *PromptTemplateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptTemplateVersionCreateBulk.OnConflict
// documentation for more info.
func (u *PromptTemplateVersionUpsertBulk) Update(set func(*PromptTemplateVersionUpsert)) *PromptTemplateVersionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptTemplateVersionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptTemplateVersionUpsertBulk) SetUpdatedAt(v time.Time) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateUpdatedAt() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *PromptTemplateVersionUpsertBulk) SetTemplateID(v int64) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *PromptTemplateVersionUpsertBulk) AddTemplateID(v int64) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateTemplateID() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateTemplateID()
	})
}

// SetVersionNo sets the "version_no" field.
func (u *PromptTemplateVersionUpsertBulk) SetVersionNo(v int) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetVersionNo(v)
	})
}

// AddVersionNo adds v to the "version_no" field.
func (u *PromptTemplateVersionUpsertBulk) AddVersionNo(v int) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddVersionNo(v)
	})
}

// UpdateVersionNo sets the "version_no" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateVersionNo() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateVersionNo()
	})
}

// SetBody sets the "body" field.
func (u *PromptTemplateVersionUpsertBulk) SetBody(v string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateBody() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateBody()
	})
}

// SetBodySha256 sets the "body_sha256" field.
func (u *PromptTemplateVersionUpsertBulk) SetBodySha256(v string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetBodySha256(v)
	})
}

// UpdateBodySha256 sets the "body_sha256" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateBodySha256() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateBodySha256()
	})
}

// SetBodyBytes sets the "body_bytes" field.
func (u *PromptTemplateVersionUpsertBulk) SetBodyBytes(v int) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetBodyBytes(v)
	})
}

// AddBodyBytes adds v to the "body_bytes" field.
func (u *PromptTemplateVersionUpsertBulk) AddBodyBytes(v int) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddBodyBytes(v)
	})
}

// UpdateBodyBytes sets the "body_bytes" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateBodyBytes() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateBodyBytes()
	})
}

// SetClientModels sets the "client_models" field.
func (u *PromptTemplateVersionUpsertBulk) SetClientModels(v []string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetClientModels(v)
	})
}

// UpdateClientModels sets the "client_models" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateClientModels() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateClientModels()
	})
}

// SetUpstreamModels sets the "upstream_models" field.
func (u *PromptTemplateVersionUpsertBulk) SetUpstreamModels(v []string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetUpstreamModels(v)
	})
}

// UpdateUpstreamModels sets the "upstream_models" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateUpstreamModels() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateUpstreamModels()
	})
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (u *PromptTemplateVersionUpsertBulk) SetSupportedProfiles(v []string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetSupportedProfiles(v)
	})
}

// UpdateSupportedProfiles sets the "supported_profiles" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateSupportedProfiles() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateSupportedProfiles()
	})
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (u *PromptTemplateVersionUpsertBulk) SetManifestSha256(v string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetManifestSha256(v)
	})
}

// UpdateManifestSha256 sets the "manifest_sha256" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateManifestSha256() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateManifestSha256()
	})
}

// SetChangeNote sets the "change_note" field.
func (u *PromptTemplateVersionUpsertBulk) SetChangeNote(v string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetChangeNote(v)
	})
}

// UpdateChangeNote sets the "change_note" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateChangeNote() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateChangeNote()
	})
}

// ClearChangeNote clears the value of the "change_note" field.
func (u *PromptTemplateVersionUpsertBulk) ClearChangeNote() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.ClearChangeNote()
	})
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (u *PromptTemplateVersionUpsertBulk) SetIdempotencyKey(v string) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetIdempotencyKey(v)
	})
}

// UpdateIdempotencyKey sets the "idempotency_key" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdateIdempotencyKey() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdateIdempotencyKey()
	})
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (u *PromptTemplateVersionUpsertBulk) ClearIdempotencyKey() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.ClearIdempotencyKey()
	})
}

// SetPublishedBy sets the "published_by" field.
func (u *PromptTemplateVersionUpsertBulk) SetPublishedBy(v int64) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetPublishedBy(v)
	})
}

// AddPublishedBy adds v to the "published_by" field.
func (u *PromptTemplateVersionUpsertBulk) AddPublishedBy(v int64) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.AddPublishedBy(v)
	})
}

// UpdatePublishedBy sets the "published_by" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdatePublishedBy() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdatePublishedBy()
	})
}

// ClearPublishedBy clears the value of the "published_by" field.
func (u *PromptTemplateVersionUpsertBulk) ClearPublishedBy() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.ClearPublishedBy()
	})
}

// SetPublishedAt sets the "published_at" field.
func (u *PromptTemplateVersionUpsertBulk) SetPublishedAt(v time.Time) *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.SetPublishedAt(v)
	})
}

// UpdatePublishedAt sets the "published_at" field to the value that was provided on create.
func (u *PromptTemplateVersionUpsertBulk) UpdatePublishedAt() *PromptTemplateVersionUpsertBulk {
	return u.Update(func(s *PromptTemplateVersionUpsert) {
		s.UpdatePublishedAt()
	})
}

// Exec executes the query.
func (u *PromptTemplateVersionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromptTemplateVersionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptTemplateVersionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptTemplateVersionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
