// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/prompttemplateversion"
)

// PromptTemplateVersionUpdate is the builder for updating PromptTemplateVersion entities.
type PromptTemplateVersionUpdate struct {
	config
	hooks    []Hook
	mutation *PromptTemplateVersionMutation
}

// Where appends a list predicates to the PromptTemplateVersionUpdate builder.
func (_u *PromptTemplateVersionUpdate) Where(ps ...predicate.PromptTemplateVersion) *PromptTemplateVersionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptTemplateVersionUpdate) SetUpdatedAt(v time.Time) *PromptTemplateVersionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *PromptTemplateVersionUpdate) SetTemplateID(v int64) *PromptTemplateVersionUpdate {
	_u.mutation.ResetTemplateID()
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableTemplateID(v *int64) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// AddTemplateID adds value to the "template_id" field.
func (_u *PromptTemplateVersionUpdate) AddTemplateID(v int64) *PromptTemplateVersionUpdate {
	_u.mutation.AddTemplateID(v)
	return _u
}

// SetVersionNo sets the "version_no" field.
func (_u *PromptTemplateVersionUpdate) SetVersionNo(v int) *PromptTemplateVersionUpdate {
	_u.mutation.ResetVersionNo()
	_u.mutation.SetVersionNo(v)
	return _u
}

// SetNillableVersionNo sets the "version_no" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableVersionNo(v *int) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetVersionNo(*v)
	}
	return _u
}

// AddVersionNo adds value to the "version_no" field.
func (_u *PromptTemplateVersionUpdate) AddVersionNo(v int) *PromptTemplateVersionUpdate {
	_u.mutation.AddVersionNo(v)
	return _u
}

// SetBody sets the "body" field.
func (_u *PromptTemplateVersionUpdate) SetBody(v string) *PromptTemplateVersionUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableBody(v *string) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetBodySha256 sets the "body_sha256" field.
func (_u *PromptTemplateVersionUpdate) SetBodySha256(v string) *PromptTemplateVersionUpdate {
	_u.mutation.SetBodySha256(v)
	return _u
}

// SetNillableBodySha256 sets the "body_sha256" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableBodySha256(v *string) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetBodySha256(*v)
	}
	return _u
}

// SetBodyBytes sets the "body_bytes" field.
func (_u *PromptTemplateVersionUpdate) SetBodyBytes(v int) *PromptTemplateVersionUpdate {
	_u.mutation.ResetBodyBytes()
	_u.mutation.SetBodyBytes(v)
	return _u
}

// SetNillableBodyBytes sets the "body_bytes" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableBodyBytes(v *int) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetBodyBytes(*v)
	}
	return _u
}

// AddBodyBytes adds value to the "body_bytes" field.
func (_u *PromptTemplateVersionUpdate) AddBodyBytes(v int) *PromptTemplateVersionUpdate {
	_u.mutation.AddBodyBytes(v)
	return _u
}

// SetClientModels sets the "client_models" field.
func (_u *PromptTemplateVersionUpdate) SetClientModels(v []string) *PromptTemplateVersionUpdate {
	_u.mutation.SetClientModels(v)
	return _u
}

// AppendClientModels appends value to the "client_models" field.
func (_u *PromptTemplateVersionUpdate) AppendClientModels(v []string) *PromptTemplateVersionUpdate {
	_u.mutation.AppendClientModels(v)
	return _u
}

// SetUpstreamModels sets the "upstream_models" field.
func (_u *PromptTemplateVersionUpdate) SetUpstreamModels(v []string) *PromptTemplateVersionUpdate {
	_u.mutation.SetUpstreamModels(v)
	return _u
}

// AppendUpstreamModels appends value to the "upstream_models" field.
func (_u *PromptTemplateVersionUpdate) AppendUpstreamModels(v []string) *PromptTemplateVersionUpdate {
	_u.mutation.AppendUpstreamModels(v)
	return _u
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (_u *PromptTemplateVersionUpdate) SetSupportedProfiles(v []string) *PromptTemplateVersionUpdate {
	_u.mutation.SetSupportedProfiles(v)
	return _u
}

// AppendSupportedProfiles appends value to the "supported_profiles" field.
func (_u *PromptTemplateVersionUpdate) AppendSupportedProfiles(v []string) *PromptTemplateVersionUpdate {
	_u.mutation.AppendSupportedProfiles(v)
	return _u
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (_u *PromptTemplateVersionUpdate) SetManifestSha256(v string) *PromptTemplateVersionUpdate {
	_u.mutation.SetManifestSha256(v)
	return _u
}

// SetNillableManifestSha256 sets the "manifest_sha256" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableManifestSha256(v *string) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetManifestSha256(*v)
	}
	return _u
}

// SetChangeNote sets the "change_note" field.
func (_u *PromptTemplateVersionUpdate) SetChangeNote(v string) *PromptTemplateVersionUpdate {
	_u.mutation.SetChangeNote(v)
	return _u
}

// SetNillableChangeNote sets the "change_note" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableChangeNote(v *string) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetChangeNote(*v)
	}
	return _u
}

// ClearChangeNote clears the value of the "change_note" field.
func (_u *PromptTemplateVersionUpdate) ClearChangeNote() *PromptTemplateVersionUpdate {
	_u.mutation.ClearChangeNote()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *PromptTemplateVersionUpdate) SetIdempotencyKey(v string) *PromptTemplateVersionUpdate {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillableIdempotencyKey(v *string) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *PromptTemplateVersionUpdate) ClearIdempotencyKey() *PromptTemplateVersionUpdate {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetPublishedBy sets the "published_by" field.
func (_u *PromptTemplateVersionUpdate) SetPublishedBy(v int64) *PromptTemplateVersionUpdate {
	_u.mutation.ResetPublishedBy()
	_u.mutation.SetPublishedBy(v)
	return _u
}

// SetNillablePublishedBy sets the "published_by" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillablePublishedBy(v *int64) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetPublishedBy(*v)
	}
	return _u
}

// AddPublishedBy adds value to the "published_by" field.
func (_u *PromptTemplateVersionUpdate) AddPublishedBy(v int64) *PromptTemplateVersionUpdate {
	_u.mutation.AddPublishedBy(v)
	return _u
}

// ClearPublishedBy clears the value of the "published_by" field.
func (_u *PromptTemplateVersionUpdate) ClearPublishedBy() *PromptTemplateVersionUpdate {
	_u.mutation.ClearPublishedBy()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PromptTemplateVersionUpdate) SetPublishedAt(v time.Time) *PromptTemplateVersionUpdate {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdate) SetNillablePublishedAt(v *time.Time) *PromptTemplateVersionUpdate {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// Mutation returns the PromptTemplateVersionMutation object of the builder.
func (_u *PromptTemplateVersionUpdate) Mutation() *PromptTemplateVersionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromptTemplateVersionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptTemplateVersionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromptTemplateVersionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptTemplateVersionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptTemplateVersionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prompttemplateversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptTemplateVersionUpdate) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := prompttemplateversion.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodySha256(); ok {
		if err := prompttemplateversion.BodySha256Validator(v); err != nil {
			return &ValidationError{Name: "body_sha256", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.body_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManifestSha256(); ok {
		if err := prompttemplateversion.ManifestSha256Validator(v); err != nil {
			return &ValidationError{Name: "manifest_sha256", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.manifest_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := prompttemplateversion.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.idempotency_key": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptTemplateVersionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prompttemplateversion.Table, prompttemplateversion.Columns, sqlgraph.NewFieldSpec(prompttemplateversion.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplateversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(prompttemplateversion.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTemplateID(); ok {
		_spec.AddField(prompttemplateversion.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VersionNo(); ok {
		_spec.SetField(prompttemplateversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNo(); ok {
		_spec.AddField(prompttemplateversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(prompttemplateversion.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodySha256(); ok {
		_spec.SetField(prompttemplateversion.FieldBodySha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyBytes(); ok {
		_spec.SetField(prompttemplateversion.FieldBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBodyBytes(); ok {
		_spec.AddField(prompttemplateversion.FieldBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClientModels(); ok {
		_spec.SetField(prompttemplateversion.FieldClientModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClientModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplateversion.FieldClientModels, value)
		})
	}
	if value, ok := _u.mutation.UpstreamModels(); ok {
		_spec.SetField(prompttemplateversion.FieldUpstreamModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplateversion.FieldUpstreamModels, value)
		})
	}
	if value, ok := _u.mutation.SupportedProfiles(); ok {
		_spec.SetField(prompttemplateversion.FieldSupportedProfiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedProfiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplateversion.FieldSupportedProfiles, value)
		})
	}
	if value, ok := _u.mutation.ManifestSha256(); ok {
		_spec.SetField(prompttemplateversion.FieldManifestSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangeNote(); ok {
		_spec.SetField(prompttemplateversion.FieldChangeNote, field.TypeString, value)
	}
	if _u.mutation.ChangeNoteCleared() {
		_spec.ClearField(prompttemplateversion.FieldChangeNote, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(prompttemplateversion.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(prompttemplateversion.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedBy(); ok {
		_spec.SetField(prompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublishedBy(); ok {
		_spec.AddField(prompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if _u.mutation.PublishedByCleared() {
		_spec.ClearField(prompttemplateversion.FieldPublishedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(prompttemplateversion.FieldPublishedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prompttemplateversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromptTemplateVersionUpdateOne is the builder for updating a single PromptTemplateVersion entity.
type PromptTemplateVersionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromptTemplateVersionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptTemplateVersionUpdateOne) SetUpdatedAt(v time.Time) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *PromptTemplateVersionUpdateOne) SetTemplateID(v int64) *PromptTemplateVersionUpdateOne {
	_u.mutation.ResetTemplateID()
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableTemplateID(v *int64) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// AddTemplateID adds value to the "template_id" field.
func (_u *PromptTemplateVersionUpdateOne) AddTemplateID(v int64) *PromptTemplateVersionUpdateOne {
	_u.mutation.AddTemplateID(v)
	return _u
}

// SetVersionNo sets the "version_no" field.
func (_u *PromptTemplateVersionUpdateOne) SetVersionNo(v int) *PromptTemplateVersionUpdateOne {
	_u.mutation.ResetVersionNo()
	_u.mutation.SetVersionNo(v)
	return _u
}

// SetNillableVersionNo sets the "version_no" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableVersionNo(v *int) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetVersionNo(*v)
	}
	return _u
}

// AddVersionNo adds value to the "version_no" field.
func (_u *PromptTemplateVersionUpdateOne) AddVersionNo(v int) *PromptTemplateVersionUpdateOne {
	_u.mutation.AddVersionNo(v)
	return _u
}

// SetBody sets the "body" field.
func (_u *PromptTemplateVersionUpdateOne) SetBody(v string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableBody(v *string) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetBodySha256 sets the "body_sha256" field.
func (_u *PromptTemplateVersionUpdateOne) SetBodySha256(v string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetBodySha256(v)
	return _u
}

// SetNillableBodySha256 sets the "body_sha256" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableBodySha256(v *string) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetBodySha256(*v)
	}
	return _u
}

// SetBodyBytes sets the "body_bytes" field.
func (_u *PromptTemplateVersionUpdateOne) SetBodyBytes(v int) *PromptTemplateVersionUpdateOne {
	_u.mutation.ResetBodyBytes()
	_u.mutation.SetBodyBytes(v)
	return _u
}

// SetNillableBodyBytes sets the "body_bytes" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableBodyBytes(v *int) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetBodyBytes(*v)
	}
	return _u
}

// AddBodyBytes adds value to the "body_bytes" field.
func (_u *PromptTemplateVersionUpdateOne) AddBodyBytes(v int) *PromptTemplateVersionUpdateOne {
	_u.mutation.AddBodyBytes(v)
	return _u
}

// SetClientModels sets the "client_models" field.
func (_u *PromptTemplateVersionUpdateOne) SetClientModels(v []string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetClientModels(v)
	return _u
}

// AppendClientModels appends value to the "client_models" field.
func (_u *PromptTemplateVersionUpdateOne) AppendClientModels(v []string) *PromptTemplateVersionUpdateOne {
	_u.mutation.AppendClientModels(v)
	return _u
}

// SetUpstreamModels sets the "upstream_models" field.
func (_u *PromptTemplateVersionUpdateOne) SetUpstreamModels(v []string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetUpstreamModels(v)
	return _u
}

// AppendUpstreamModels appends value to the "upstream_models" field.
func (_u *PromptTemplateVersionUpdateOne) AppendUpstreamModels(v []string) *PromptTemplateVersionUpdateOne {
	_u.mutation.AppendUpstreamModels(v)
	return _u
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (_u *PromptTemplateVersionUpdateOne) SetSupportedProfiles(v []string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetSupportedProfiles(v)
	return _u
}

// AppendSupportedProfiles appends value to the "supported_profiles" field.
func (_u *PromptTemplateVersionUpdateOne) AppendSupportedProfiles(v []string) *PromptTemplateVersionUpdateOne {
	_u.mutation.AppendSupportedProfiles(v)
	return _u
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (_u *PromptTemplateVersionUpdateOne) SetManifestSha256(v string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetManifestSha256(v)
	return _u
}

// SetNillableManifestSha256 sets the "manifest_sha256" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableManifestSha256(v *string) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetManifestSha256(*v)
	}
	return _u
}

// SetChangeNote sets the "change_note" field.
func (_u *PromptTemplateVersionUpdateOne) SetChangeNote(v string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetChangeNote(v)
	return _u
}

// SetNillableChangeNote sets the "change_note" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableChangeNote(v *string) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetChangeNote(*v)
	}
	return _u
}

// ClearChangeNote clears the value of the "change_note" field.
func (_u *PromptTemplateVersionUpdateOne) ClearChangeNote() *PromptTemplateVersionUpdateOne {
	_u.mutation.ClearChangeNote()
	return _u
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_u *PromptTemplateVersionUpdateOne) SetIdempotencyKey(v string) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetIdempotencyKey(v)
	return _u
}

// SetNillableIdempotencyKey sets the "idempotency_key" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillableIdempotencyKey(v *string) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetIdempotencyKey(*v)
	}
	return _u
}

// ClearIdempotencyKey clears the value of the "idempotency_key" field.
func (_u *PromptTemplateVersionUpdateOne) ClearIdempotencyKey() *PromptTemplateVersionUpdateOne {
	_u.mutation.ClearIdempotencyKey()
	return _u
}

// SetPublishedBy sets the "published_by" field.
func (_u *PromptTemplateVersionUpdateOne) SetPublishedBy(v int64) *PromptTemplateVersionUpdateOne {
	_u.mutation.ResetPublishedBy()
	_u.mutation.SetPublishedBy(v)
	return _u
}

// SetNillablePublishedBy sets the "published_by" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillablePublishedBy(v *int64) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetPublishedBy(*v)
	}
	return _u
}

// AddPublishedBy adds value to the "published_by" field.
func (_u *PromptTemplateVersionUpdateOne) AddPublishedBy(v int64) *PromptTemplateVersionUpdateOne {
	_u.mutation.AddPublishedBy(v)
	return _u
}

// ClearPublishedBy clears the value of the "published_by" field.
func (_u *PromptTemplateVersionUpdateOne) ClearPublishedBy() *PromptTemplateVersionUpdateOne {
	_u.mutation.ClearPublishedBy()
	return _u
}

// SetPublishedAt sets the "published_at" field.
func (_u *PromptTemplateVersionUpdateOne) SetPublishedAt(v time.Time) *PromptTemplateVersionUpdateOne {
	_u.mutation.SetPublishedAt(v)
	return _u
}

// SetNillablePublishedAt sets the "published_at" field if the given value is not nil.
func (_u *PromptTemplateVersionUpdateOne) SetNillablePublishedAt(v *time.Time) *PromptTemplateVersionUpdateOne {
	if v != nil {
		_u.SetPublishedAt(*v)
	}
	return _u
}

// Mutation returns the PromptTemplateVersionMutation object of the builder.
func (_u *PromptTemplateVersionUpdateOne) Mutation() *PromptTemplateVersionMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromptTemplateVersionUpdate builder.
func (_u *PromptTemplateVersionUpdateOne) Where(ps ...predicate.PromptTemplateVersion) *PromptTemplateVersionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromptTemplateVersionUpdateOne) Select(field string, fields ...string) *PromptTemplateVersionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromptTemplateVersion entity.
func (_u *PromptTemplateVersionUpdateOne) Save(ctx context.Context) (*PromptTemplateVersion, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptTemplateVersionUpdateOne) SaveX(ctx context.Context) *PromptTemplateVersion {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromptTemplateVersionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptTemplateVersionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptTemplateVersionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prompttemplateversion.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptTemplateVersionUpdateOne) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := prompttemplateversion.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.body": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BodySha256(); ok {
		if err := prompttemplateversion.BodySha256Validator(v); err != nil {
			return &ValidationError{Name: "body_sha256", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.body_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ManifestSha256(); ok {
		if err := prompttemplateversion.ManifestSha256Validator(v); err != nil {
			return &ValidationError{Name: "manifest_sha256", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.manifest_sha256": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IdempotencyKey(); ok {
		if err := prompttemplateversion.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateVersion.idempotency_key": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptTemplateVersionUpdateOne) sqlSave(ctx context.Context) (_node *PromptTemplateVersion, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prompttemplateversion.Table, prompttemplateversion.Columns, sqlgraph.NewFieldSpec(prompttemplateversion.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromptTemplateVersion.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prompttemplateversion.FieldID)
		for _, f := range fields {
			if !prompttemplateversion.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prompttemplateversion.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplateversion.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(prompttemplateversion.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTemplateID(); ok {
		_spec.AddField(prompttemplateversion.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.VersionNo(); ok {
		_spec.SetField(prompttemplateversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedVersionNo(); ok {
		_spec.AddField(prompttemplateversion.FieldVersionNo, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(prompttemplateversion.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodySha256(); ok {
		_spec.SetField(prompttemplateversion.FieldBodySha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.BodyBytes(); ok {
		_spec.SetField(prompttemplateversion.FieldBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBodyBytes(); ok {
		_spec.AddField(prompttemplateversion.FieldBodyBytes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ClientModels(); ok {
		_spec.SetField(prompttemplateversion.FieldClientModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClientModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplateversion.FieldClientModels, value)
		})
	}
	if value, ok := _u.mutation.UpstreamModels(); ok {
		_spec.SetField(prompttemplateversion.FieldUpstreamModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplateversion.FieldUpstreamModels, value)
		})
	}
	if value, ok := _u.mutation.SupportedProfiles(); ok {
		_spec.SetField(prompttemplateversion.FieldSupportedProfiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedProfiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplateversion.FieldSupportedProfiles, value)
		})
	}
	if value, ok := _u.mutation.ManifestSha256(); ok {
		_spec.SetField(prompttemplateversion.FieldManifestSha256, field.TypeString, value)
	}
	if value, ok := _u.mutation.ChangeNote(); ok {
		_spec.SetField(prompttemplateversion.FieldChangeNote, field.TypeString, value)
	}
	if _u.mutation.ChangeNoteCleared() {
		_spec.ClearField(prompttemplateversion.FieldChangeNote, field.TypeString)
	}
	if value, ok := _u.mutation.IdempotencyKey(); ok {
		_spec.SetField(prompttemplateversion.FieldIdempotencyKey, field.TypeString, value)
	}
	if _u.mutation.IdempotencyKeyCleared() {
		_spec.ClearField(prompttemplateversion.FieldIdempotencyKey, field.TypeString)
	}
	if value, ok := _u.mutation.PublishedBy(); ok {
		_spec.SetField(prompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedPublishedBy(); ok {
		_spec.AddField(prompttemplateversion.FieldPublishedBy, field.TypeInt64, value)
	}
	if _u.mutation.PublishedByCleared() {
		_spec.ClearField(prompttemplateversion.FieldPublishedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.PublishedAt(); ok {
		_spec.SetField(prompttemplateversion.FieldPublishedAt, field.TypeTime, value)
	}
	_node = &PromptTemplateVersion{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prompttemplateversion.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
