// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/promptrequestevent"
)

// PromptRequestEventCreate is the builder for creating a PromptRequestEvent entity.
type PromptRequestEventCreate struct {
	config
	mutation *PromptRequestEventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptRequestEventCreate) SetCreatedAt(v time.Time) *PromptRequestEventCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableCreatedAt(v *time.Time) *PromptRequestEventCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromptRequestEventCreate) SetUpdatedAt(v time.Time) *PromptRequestEventCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableUpdatedAt(v *time.Time) *PromptRequestEventCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetRequestID sets the "request_id" field.
func (_c *PromptRequestEventCreate) SetRequestID(v string) *PromptRequestEventCreate {
	_c.mutation.SetRequestID(v)
	return _c
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableRequestID(v *string) *PromptRequestEventCreate {
	if v != nil {
		_c.SetRequestID(*v)
	}
	return _c
}

// SetAttemptNo sets the "attempt_no" field.
func (_c *PromptRequestEventCreate) SetAttemptNo(v int) *PromptRequestEventCreate {
	_c.mutation.SetAttemptNo(v)
	return _c
}

// SetNillableAttemptNo sets the "attempt_no" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableAttemptNo(v *int) *PromptRequestEventCreate {
	if v != nil {
		_c.SetAttemptNo(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PromptRequestEventCreate) SetGroupID(v int64) *PromptRequestEventCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableGroupID(v *int64) *PromptRequestEventCreate {
	if v != nil {
		_c.SetGroupID(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *PromptRequestEventCreate) SetAccountID(v int64) *PromptRequestEventCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableAccountID(v *int64) *PromptRequestEventCreate {
	if v != nil {
		_c.SetAccountID(*v)
	}
	return _c
}

// SetClientModel sets the "client_model" field.
func (_c *PromptRequestEventCreate) SetClientModel(v string) *PromptRequestEventCreate {
	_c.mutation.SetClientModel(v)
	return _c
}

// SetNillableClientModel sets the "client_model" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableClientModel(v *string) *PromptRequestEventCreate {
	if v != nil {
		_c.SetClientModel(*v)
	}
	return _c
}

// SetUpstreamModel sets the "upstream_model" field.
func (_c *PromptRequestEventCreate) SetUpstreamModel(v string) *PromptRequestEventCreate {
	_c.mutation.SetUpstreamModel(v)
	return _c
}

// SetNillableUpstreamModel sets the "upstream_model" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableUpstreamModel(v *string) *PromptRequestEventCreate {
	if v != nil {
		_c.SetUpstreamModel(*v)
	}
	return _c
}

// SetOutboundProfile sets the "outbound_profile" field.
func (_c *PromptRequestEventCreate) SetOutboundProfile(v string) *PromptRequestEventCreate {
	_c.mutation.SetOutboundProfile(v)
	return _c
}

// SetNillableOutboundProfile sets the "outbound_profile" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableOutboundProfile(v *string) *PromptRequestEventCreate {
	if v != nil {
		_c.SetOutboundProfile(*v)
	}
	return _c
}

// SetBindingSource sets the "binding_source" field.
func (_c *PromptRequestEventCreate) SetBindingSource(v string) *PromptRequestEventCreate {
	_c.mutation.SetBindingSource(v)
	return _c
}

// SetNillableBindingSource sets the "binding_source" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableBindingSource(v *string) *PromptRequestEventCreate {
	if v != nil {
		_c.SetBindingSource(*v)
	}
	return _c
}

// SetVersionID sets the "version_id" field.
func (_c *PromptRequestEventCreate) SetVersionID(v int64) *PromptRequestEventCreate {
	_c.mutation.SetVersionID(v)
	return _c
}

// SetNillableVersionID sets the "version_id" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableVersionID(v *int64) *PromptRequestEventCreate {
	if v != nil {
		_c.SetVersionID(*v)
	}
	return _c
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (_c *PromptRequestEventCreate) SetManifestSha256(v string) *PromptRequestEventCreate {
	_c.mutation.SetManifestSha256(v)
	return _c
}

// SetNillableManifestSha256 sets the "manifest_sha256" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableManifestSha256(v *string) *PromptRequestEventCreate {
	if v != nil {
		_c.SetManifestSha256(*v)
	}
	return _c
}

// SetApplied sets the "applied" field.
func (_c *PromptRequestEventCreate) SetApplied(v bool) *PromptRequestEventCreate {
	_c.mutation.SetApplied(v)
	return _c
}

// SetNillableApplied sets the "applied" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableApplied(v *bool) *PromptRequestEventCreate {
	if v != nil {
		_c.SetApplied(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *PromptRequestEventCreate) SetReason(v string) *PromptRequestEventCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetAddedBytes sets the "added_bytes" field.
func (_c *PromptRequestEventCreate) SetAddedBytes(v int) *PromptRequestEventCreate {
	_c.mutation.SetAddedBytes(v)
	return _c
}

// SetNillableAddedBytes sets the "added_bytes" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableAddedBytes(v *int) *PromptRequestEventCreate {
	if v != nil {
		_c.SetAddedBytes(*v)
	}
	return _c
}

// SetApplyDurationMs sets the "apply_duration_ms" field.
func (_c *PromptRequestEventCreate) SetApplyDurationMs(v int) *PromptRequestEventCreate {
	_c.mutation.SetApplyDurationMs(v)
	return _c
}

// SetNillableApplyDurationMs sets the "apply_duration_ms" field if the given value is not nil.
func (_c *PromptRequestEventCreate) SetNillableApplyDurationMs(v *int) *PromptRequestEventCreate {
	if v != nil {
		_c.SetApplyDurationMs(*v)
	}
	return _c
}

// Mutation returns the PromptRequestEventMutation object of the builder.
func (_c *PromptRequestEventCreate) Mutation() *PromptRequestEventMutation {
	return _c.mutation
}

// Save creates the PromptRequestEvent in the database.
func (_c *PromptRequestEventCreate) Save(ctx context.Context) (*PromptRequestEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptRequestEventCreate) SaveX(ctx context.Context) *PromptRequestEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptRequestEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptRequestEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptRequestEventCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := promptrequestevent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := promptrequestevent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.AttemptNo(); !ok {
		v := promptrequestevent.DefaultAttemptNo
		_c.mutation.SetAttemptNo(v)
	}
	if _, ok := _c.mutation.Applied(); !ok {
		v := promptrequestevent.DefaultApplied
		_c.mutation.SetApplied(v)
	}
	if _, ok := _c.mutation.AddedBytes(); !ok {
		v := promptrequestevent.DefaultAddedBytes
		_c.mutation.SetAddedBytes(v)
	}
	if _, ok := _c.mutation.ApplyDurationMs(); !ok {
		v := promptrequestevent.DefaultApplyDurationMs
		_c.mutation.SetApplyDurationMs(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptRequestEventCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromptRequestEvent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromptRequestEvent.updated_at"`)}
	}
	if v, ok := _c.mutation.RequestID(); ok {
		if err := promptrequestevent.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "PromptRequestEvent.request_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AttemptNo(); !ok {
		return &ValidationError{Name: "attempt_no", err: errors.New(`ent: missing required field "PromptRequestEvent.attempt_no"`)}
	}
	if v, ok := _c.mutation.ClientModel(); ok {
		if err := promptrequestevent.ClientModelValidator(v); err != nil {
			return &ValidationError{Name: "client_model", err: fmt.Errorf(`ent: validator failed for field "PromptRequestEvent.client_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.UpstreamModel(); ok {
		if err := promptrequestevent.UpstreamModelValidator(v); err != nil {
			return &ValidationError{Name: "upstream_model", err: fmt.Errorf(`ent: validator failed for field "PromptRequestEvent.upstream_model": %w`, err)}
		}
	}
	if v, ok := _c.mutation.OutboundProfile(); ok {
		if err := promptrequestevent.OutboundProfileValidator(v); err != nil {
			return &ValidationError{Name: "outbound_profile", err: fmt.Errorf(`ent: validator failed for field "PromptRequestEvent.outbound_profile": %w`, err)}
		}
	}
	if v, ok := _c.mutation.BindingSource(); ok {
		if err := promptrequestevent.BindingSourceValidator(v); err != nil {
			return &ValidationError{Name: "binding_source", err: fmt.Errorf(`ent: validator failed for field "PromptRequestEvent.binding_source": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ManifestSha256(); ok {
		if err := promptrequestevent.ManifestSha256Validator(v); err != nil {
			return &ValidationError{Name: "manifest_sha256", err: fmt.Errorf(`ent: validator failed for field "PromptRequestEvent.manifest_sha256": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Applied(); !ok {
		return &ValidationError{Name: "applied", err: errors.New(`ent: missing required field "PromptRequestEvent.applied"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "PromptRequestEvent.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := promptrequestevent.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "PromptRequestEvent.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AddedBytes(); !ok {
		return &ValidationError{Name: "added_bytes", err: errors.New(`ent: missing required field "PromptRequestEvent.added_bytes"`)}
	}
	if _, ok := _c.mutation.ApplyDurationMs(); !ok {
		return &ValidationError{Name: "apply_duration_ms", err: errors.New(`ent: missing required field "PromptRequestEvent.apply_duration_ms"`)}
	}
	return nil
}

func (_c *PromptRequestEventCreate) sqlSave(ctx context.Context) (*PromptRequestEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptRequestEventCreate) createSpec() (*PromptRequestEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptRequestEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(promptrequestevent.Table, sqlgraph.NewFieldSpec(promptrequestevent.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(promptrequestevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(promptrequestevent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.RequestID(); ok {
		_spec.SetField(promptrequestevent.FieldRequestID, field.TypeString, value)
		_node.RequestID = &value
	}
	if value, ok := _c.mutation.AttemptNo(); ok {
		_spec.SetField(promptrequestevent.FieldAttemptNo, field.TypeInt, value)
		_node.AttemptNo = value
	}
	if value, ok := _c.mutation.GroupID(); ok {
		_spec.SetField(promptrequestevent.FieldGroupID, field.TypeInt64, value)
		_node.GroupID = &value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(promptrequestevent.FieldAccountID, field.TypeInt64, value)
		_node.AccountID = &value
	}
	if value, ok := _c.mutation.ClientModel(); ok {
		_spec.SetField(promptrequestevent.FieldClientModel, field.TypeString, value)
		_node.ClientModel = &value
	}
	if value, ok := _c.mutation.UpstreamModel(); ok {
		_spec.SetField(promptrequestevent.FieldUpstreamModel, field.TypeString, value)
		_node.UpstreamModel = &value
	}
	if value, ok := _c.mutation.OutboundProfile(); ok {
		_spec.SetField(promptrequestevent.FieldOutboundProfile, field.TypeString, value)
		_node.OutboundProfile = &value
	}
	if value, ok := _c.mutation.BindingSource(); ok {
		_spec.SetField(promptrequestevent.FieldBindingSource, field.TypeString, value)
		_node.BindingSource = &value
	}
	if value, ok := _c.mutation.VersionID(); ok {
		_spec.SetField(promptrequestevent.FieldVersionID, field.TypeInt64, value)
		_node.VersionID = &value
	}
	if value, ok := _c.mutation.ManifestSha256(); ok {
		_spec.SetField(promptrequestevent.FieldManifestSha256, field.TypeString, value)
		_node.ManifestSha256 = &value
	}
	if value, ok := _c.mutation.Applied(); ok {
		_spec.SetField(promptrequestevent.FieldApplied, field.TypeBool, value)
		_node.Applied = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(promptrequestevent.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.AddedBytes(); ok {
		_spec.SetField(promptrequestevent.FieldAddedBytes, field.TypeInt, value)
		_node.AddedBytes = value
	}
	if value, ok := _c.mutation.ApplyDurationMs(); ok {
		_spec.SetField(promptrequestevent.FieldApplyDurationMs, field.TypeInt, value)
		_node.ApplyDurationMs = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptRequestEvent.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptRequestEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptRequestEventCreate) OnConflict(opts ...sql.ConflictOption) *PromptRequestEventUpsertOne {
	_c.conflict = opts
	return &PromptRequestEventUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptRequestEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptRequestEventCreate) OnConflictColumns(columns ...string) *PromptRequestEventUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptRequestEventUpsertOne{
		create: _c,
	}
}

type (
	// PromptRequestEventUpsertOne is the builder for "upsert"-ing
	//  one PromptRequestEvent node.
	PromptRequestEventUpsertOne struct {
		create *PromptRequestEventCreate
	}

	// PromptRequestEventUpsert is the "OnConflict" setter.
	PromptRequestEventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptRequestEventUpsert) SetUpdatedAt(v time.Time) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateUpdatedAt() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldUpdatedAt)
	return u
}

// SetRequestID sets the "request_id" field.
func (u *PromptRequestEventUpsert) SetRequestID(v string) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldRequestID, v)
	return u
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateRequestID() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldRequestID)
	return u
}

// ClearRequestID clears the value of the "request_id" field.
func (u *PromptRequestEventUpsert) ClearRequestID() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldRequestID)
	return u
}

// SetAttemptNo sets the "attempt_no" field.
func (u *PromptRequestEventUpsert) SetAttemptNo(v int) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldAttemptNo, v)
	return u
}

// UpdateAttemptNo sets the "attempt_no" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateAttemptNo() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldAttemptNo)
	return u
}

// AddAttemptNo adds v to the "attempt_no" field.
func (u *PromptRequestEventUpsert) AddAttemptNo(v int) *PromptRequestEventUpsert {
	u.Add(promptrequestevent.FieldAttemptNo, v)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *PromptRequestEventUpsert) SetGroupID(v int64) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateGroupID() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldGroupID)
	return u
}

// AddGroupID adds v to the "group_id" field.
func (u *PromptRequestEventUpsert) AddGroupID(v int64) *PromptRequestEventUpsert {
	u.Add(promptrequestevent.FieldGroupID, v)
	return u
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PromptRequestEventUpsert) ClearGroupID() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *PromptRequestEventUpsert) SetAccountID(v int64) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateAccountID() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldAccountID)
	return u
}

// AddAccountID adds v to the "account_id" field.
func (u *PromptRequestEventUpsert) AddAccountID(v int64) *PromptRequestEventUpsert {
	u.Add(promptrequestevent.FieldAccountID, v)
	return u
}

// ClearAccountID clears the value of the "account_id" field.
func (u *PromptRequestEventUpsert) ClearAccountID() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldAccountID)
	return u
}

// SetClientModel sets the "client_model" field.
func (u *PromptRequestEventUpsert) SetClientModel(v string) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldClientModel, v)
	return u
}

// UpdateClientModel sets the "client_model" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateClientModel() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldClientModel)
	return u
}

// ClearClientModel clears the value of the "client_model" field.
func (u *PromptRequestEventUpsert) ClearClientModel() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldClientModel)
	return u
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PromptRequestEventUpsert) SetUpstreamModel(v string) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldUpstreamModel, v)
	return u
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateUpstreamModel() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldUpstreamModel)
	return u
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *PromptRequestEventUpsert) ClearUpstreamModel() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldUpstreamModel)
	return u
}

// SetOutboundProfile sets the "outbound_profile" field.
func (u *PromptRequestEventUpsert) SetOutboundProfile(v string) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldOutboundProfile, v)
	return u
}

// UpdateOutboundProfile sets the "outbound_profile" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateOutboundProfile() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldOutboundProfile)
	return u
}

// ClearOutboundProfile clears the value of the "outbound_profile" field.
func (u *PromptRequestEventUpsert) ClearOutboundProfile() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldOutboundProfile)
	return u
}

// SetBindingSource sets the "binding_source" field.
func (u *PromptRequestEventUpsert) SetBindingSource(v string) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldBindingSource, v)
	return u
}

// UpdateBindingSource sets the "binding_source" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateBindingSource() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldBindingSource)
	return u
}

// ClearBindingSource clears the value of the "binding_source" field.
func (u *PromptRequestEventUpsert) ClearBindingSource() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldBindingSource)
	return u
}

// SetVersionID sets the "version_id" field.
func (u *PromptRequestEventUpsert) SetVersionID(v int64) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldVersionID, v)
	return u
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateVersionID() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldVersionID)
	return u
}

// AddVersionID adds v to the "version_id" field.
func (u *PromptRequestEventUpsert) AddVersionID(v int64) *PromptRequestEventUpsert {
	u.Add(promptrequestevent.FieldVersionID, v)
	return u
}

// ClearVersionID clears the value of the "version_id" field.
func (u *PromptRequestEventUpsert) ClearVersionID() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldVersionID)
	return u
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (u *PromptRequestEventUpsert) SetManifestSha256(v string) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldManifestSha256, v)
	return u
}

// UpdateManifestSha256 sets the "manifest_sha256" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateManifestSha256() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldManifestSha256)
	return u
}

// ClearManifestSha256 clears the value of the "manifest_sha256" field.
func (u *PromptRequestEventUpsert) ClearManifestSha256() *PromptRequestEventUpsert {
	u.SetNull(promptrequestevent.FieldManifestSha256)
	return u
}

// SetApplied sets the "applied" field.
func (u *PromptRequestEventUpsert) SetApplied(v bool) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldApplied, v)
	return u
}

// UpdateApplied sets the "applied" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateApplied() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldApplied)
	return u
}

// SetReason sets the "reason" field.
func (u *PromptRequestEventUpsert) SetReason(v string) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateReason() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldReason)
	return u
}

// SetAddedBytes sets the "added_bytes" field.
func (u *PromptRequestEventUpsert) SetAddedBytes(v int) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldAddedBytes, v)
	return u
}

// UpdateAddedBytes sets the "added_bytes" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateAddedBytes() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldAddedBytes)
	return u
}

// AddAddedBytes adds v to the "added_bytes" field.
func (u *PromptRequestEventUpsert) AddAddedBytes(v int) *PromptRequestEventUpsert {
	u.Add(promptrequestevent.FieldAddedBytes, v)
	return u
}

// SetApplyDurationMs sets the "apply_duration_ms" field.
func (u *PromptRequestEventUpsert) SetApplyDurationMs(v int) *PromptRequestEventUpsert {
	u.Set(promptrequestevent.FieldApplyDurationMs, v)
	return u
}

// UpdateApplyDurationMs sets the "apply_duration_ms" field to the value that was provided on create.
func (u *PromptRequestEventUpsert) UpdateApplyDurationMs() *PromptRequestEventUpsert {
	u.SetExcluded(promptrequestevent.FieldApplyDurationMs)
	return u
}

// AddApplyDurationMs adds v to the "apply_duration_ms" field.
func (u *PromptRequestEventUpsert) AddApplyDurationMs(v int) *PromptRequestEventUpsert {
	u.Add(promptrequestevent.FieldApplyDurationMs, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromptRequestEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptRequestEventUpsertOne) UpdateNewValues() *PromptRequestEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(promptrequestevent.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptRequestEvent.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromptRequestEventUpsertOne) Ignore() *PromptRequestEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptRequestEventUpsertOne) DoNothing() *PromptRequestEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptRequestEventCreate.OnConflict
// documentation for more info.
func (u *PromptRequestEventUpsertOne) Update(set func(*PromptRequestEventUpsert)) *PromptRequestEventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptRequestEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptRequestEventUpsertOne) SetUpdatedAt(v time.Time) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateUpdatedAt() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *PromptRequestEventUpsertOne) SetRequestID(v string) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateRequestID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *PromptRequestEventUpsertOne) ClearRequestID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearRequestID()
	})
}

// SetAttemptNo sets the "attempt_no" field.
func (u *PromptRequestEventUpsertOne) SetAttemptNo(v int) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetAttemptNo(v)
	})
}

// AddAttemptNo adds v to the "attempt_no" field.
func (u *PromptRequestEventUpsertOne) AddAttemptNo(v int) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddAttemptNo(v)
	})
}

// UpdateAttemptNo sets the "attempt_no" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateAttemptNo() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateAttemptNo()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PromptRequestEventUpsertOne) SetGroupID(v int64) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PromptRequestEventUpsertOne) AddGroupID(v int64) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateGroupID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PromptRequestEventUpsertOne) ClearGroupID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *PromptRequestEventUpsertOne) SetAccountID(v int64) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *PromptRequestEventUpsertOne) AddAccountID(v int64) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateAccountID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *PromptRequestEventUpsertOne) ClearAccountID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearAccountID()
	})
}

// SetClientModel sets the "client_model" field.
func (u *PromptRequestEventUpsertOne) SetClientModel(v string) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetClientModel(v)
	})
}

// UpdateClientModel sets the "client_model" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateClientModel() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateClientModel()
	})
}

// ClearClientModel clears the value of the "client_model" field.
func (u *PromptRequestEventUpsertOne) ClearClientModel() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearClientModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PromptRequestEventUpsertOne) SetUpstreamModel(v string) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateUpstreamModel() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateUpstreamModel()
	})
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *PromptRequestEventUpsertOne) ClearUpstreamModel() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearUpstreamModel()
	})
}

// SetOutboundProfile sets the "outbound_profile" field.
func (u *PromptRequestEventUpsertOne) SetOutboundProfile(v string) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetOutboundProfile(v)
	})
}

// UpdateOutboundProfile sets the "outbound_profile" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateOutboundProfile() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateOutboundProfile()
	})
}

// ClearOutboundProfile clears the value of the "outbound_profile" field.
func (u *PromptRequestEventUpsertOne) ClearOutboundProfile() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearOutboundProfile()
	})
}

// SetBindingSource sets the "binding_source" field.
func (u *PromptRequestEventUpsertOne) SetBindingSource(v string) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetBindingSource(v)
	})
}

// UpdateBindingSource sets the "binding_source" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateBindingSource() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateBindingSource()
	})
}

// ClearBindingSource clears the value of the "binding_source" field.
func (u *PromptRequestEventUpsertOne) ClearBindingSource() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearBindingSource()
	})
}

// SetVersionID sets the "version_id" field.
func (u *PromptRequestEventUpsertOne) SetVersionID(v int64) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetVersionID(v)
	})
}

// AddVersionID adds v to the "version_id" field.
func (u *PromptRequestEventUpsertOne) AddVersionID(v int64) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddVersionID(v)
	})
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateVersionID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateVersionID()
	})
}

// ClearVersionID clears the value of the "version_id" field.
func (u *PromptRequestEventUpsertOne) ClearVersionID() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearVersionID()
	})
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (u *PromptRequestEventUpsertOne) SetManifestSha256(v string) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetManifestSha256(v)
	})
}

// UpdateManifestSha256 sets the "manifest_sha256" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateManifestSha256() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateManifestSha256()
	})
}

// ClearManifestSha256 clears the value of the "manifest_sha256" field.
func (u *PromptRequestEventUpsertOne) ClearManifestSha256() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearManifestSha256()
	})
}

// SetApplied sets the "applied" field.
func (u *PromptRequestEventUpsertOne) SetApplied(v bool) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetApplied(v)
	})
}

// UpdateApplied sets the "applied" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateApplied() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateApplied()
	})
}

// SetReason sets the "reason" field.
func (u *PromptRequestEventUpsertOne) SetReason(v string) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateReason() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateReason()
	})
}

// SetAddedBytes sets the "added_bytes" field.
func (u *PromptRequestEventUpsertOne) SetAddedBytes(v int) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetAddedBytes(v)
	})
}

// AddAddedBytes adds v to the "added_bytes" field.
func (u *PromptRequestEventUpsertOne) AddAddedBytes(v int) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddAddedBytes(v)
	})
}

// UpdateAddedBytes sets the "added_bytes" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateAddedBytes() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateAddedBytes()
	})
}

// SetApplyDurationMs sets the "apply_duration_ms" field.
func (u *PromptRequestEventUpsertOne) SetApplyDurationMs(v int) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetApplyDurationMs(v)
	})
}

// AddApplyDurationMs adds v to the "apply_duration_ms" field.
func (u *PromptRequestEventUpsertOne) AddApplyDurationMs(v int) *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddApplyDurationMs(v)
	})
}

// UpdateApplyDurationMs sets the "apply_duration_ms" field to the value that was provided on create.
func (u *PromptRequestEventUpsertOne) UpdateApplyDurationMs() *PromptRequestEventUpsertOne {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateApplyDurationMs()
	})
}

// Exec executes the query.
func (u *PromptRequestEventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptRequestEventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptRequestEventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromptRequestEventUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromptRequestEventUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromptRequestEventCreateBulk is the builder for creating many PromptRequestEvent entities in bulk.
type PromptRequestEventCreateBulk struct {
	config
	err      error
	builders []*PromptRequestEventCreate
	conflict []sql.ConflictOption
}

// Save creates the PromptRequestEvent entities in the database.
func (_c *PromptRequestEventCreateBulk) Save(ctx context.Context) ([]*PromptRequestEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptRequestEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptRequestEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptRequestEventCreateBulk) SaveX(ctx context.Context) []*PromptRequestEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptRequestEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptRequestEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptRequestEvent.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptRequestEventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptRequestEventCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromptRequestEventUpsertBulk {
	_c.conflict = opts
	return &PromptRequestEventUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptRequestEvent.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptRequestEventCreateBulk) OnConflictColumns(columns ...string) *PromptRequestEventUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptRequestEventUpsertBulk{
		create: _c,
	}
}

// PromptRequestEventUpsertBulk is the builder for "upsert"-ing
// a bulk of PromptRequestEvent nodes.
type PromptRequestEventUpsertBulk struct {
	create *PromptRequestEventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromptRequestEvent.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptRequestEventUpsertBulk) UpdateNewValues() *PromptRequestEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(promptrequestevent.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptRequestEvent.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromptRequestEventUpsertBulk) Ignore() *PromptRequestEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptRequestEventUpsertBulk) DoNothing() *PromptRequestEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptRequestEventCreateBulk.OnConflict
// documentation for more info.
func (u *PromptRequestEventUpsertBulk) Update(set func(*PromptRequestEventUpsert)) *PromptRequestEventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptRequestEventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptRequestEventUpsertBulk) SetUpdatedAt(v time.Time) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateUpdatedAt() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetRequestID sets the "request_id" field.
func (u *PromptRequestEventUpsertBulk) SetRequestID(v string) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetRequestID(v)
	})
}

// UpdateRequestID sets the "request_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateRequestID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateRequestID()
	})
}

// ClearRequestID clears the value of the "request_id" field.
func (u *PromptRequestEventUpsertBulk) ClearRequestID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearRequestID()
	})
}

// SetAttemptNo sets the "attempt_no" field.
func (u *PromptRequestEventUpsertBulk) SetAttemptNo(v int) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetAttemptNo(v)
	})
}

// AddAttemptNo adds v to the "attempt_no" field.
func (u *PromptRequestEventUpsertBulk) AddAttemptNo(v int) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddAttemptNo(v)
	})
}

// UpdateAttemptNo sets the "attempt_no" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateAttemptNo() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateAttemptNo()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PromptRequestEventUpsertBulk) SetGroupID(v int64) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetGroupID(v)
	})
}

// AddGroupID adds v to the "group_id" field.
func (u *PromptRequestEventUpsertBulk) AddGroupID(v int64) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateGroupID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateGroupID()
	})
}

// ClearGroupID clears the value of the "group_id" field.
func (u *PromptRequestEventUpsertBulk) ClearGroupID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *PromptRequestEventUpsertBulk) SetAccountID(v int64) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetAccountID(v)
	})
}

// AddAccountID adds v to the "account_id" field.
func (u *PromptRequestEventUpsertBulk) AddAccountID(v int64) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateAccountID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateAccountID()
	})
}

// ClearAccountID clears the value of the "account_id" field.
func (u *PromptRequestEventUpsertBulk) ClearAccountID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearAccountID()
	})
}

// SetClientModel sets the "client_model" field.
func (u *PromptRequestEventUpsertBulk) SetClientModel(v string) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetClientModel(v)
	})
}

// UpdateClientModel sets the "client_model" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateClientModel() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateClientModel()
	})
}

// ClearClientModel clears the value of the "client_model" field.
func (u *PromptRequestEventUpsertBulk) ClearClientModel() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearClientModel()
	})
}

// SetUpstreamModel sets the "upstream_model" field.
func (u *PromptRequestEventUpsertBulk) SetUpstreamModel(v string) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetUpstreamModel(v)
	})
}

// UpdateUpstreamModel sets the "upstream_model" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateUpstreamModel() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateUpstreamModel()
	})
}

// ClearUpstreamModel clears the value of the "upstream_model" field.
func (u *PromptRequestEventUpsertBulk) ClearUpstreamModel() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearUpstreamModel()
	})
}

// SetOutboundProfile sets the "outbound_profile" field.
func (u *PromptRequestEventUpsertBulk) SetOutboundProfile(v string) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetOutboundProfile(v)
	})
}

// UpdateOutboundProfile sets the "outbound_profile" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateOutboundProfile() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateOutboundProfile()
	})
}

// ClearOutboundProfile clears the value of the "outbound_profile" field.
func (u *PromptRequestEventUpsertBulk) ClearOutboundProfile() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearOutboundProfile()
	})
}

// SetBindingSource sets the "binding_source" field.
func (u *PromptRequestEventUpsertBulk) SetBindingSource(v string) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetBindingSource(v)
	})
}

// UpdateBindingSource sets the "binding_source" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateBindingSource() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateBindingSource()
	})
}

// ClearBindingSource clears the value of the "binding_source" field.
func (u *PromptRequestEventUpsertBulk) ClearBindingSource() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearBindingSource()
	})
}

// SetVersionID sets the "version_id" field.
func (u *PromptRequestEventUpsertBulk) SetVersionID(v int64) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetVersionID(v)
	})
}

// AddVersionID adds v to the "version_id" field.
func (u *PromptRequestEventUpsertBulk) AddVersionID(v int64) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddVersionID(v)
	})
}

// UpdateVersionID sets the "version_id" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateVersionID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateVersionID()
	})
}

// ClearVersionID clears the value of the "version_id" field.
func (u *PromptRequestEventUpsertBulk) ClearVersionID() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearVersionID()
	})
}

// SetManifestSha256 sets the "manifest_sha256" field.
func (u *PromptRequestEventUpsertBulk) SetManifestSha256(v string) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetManifestSha256(v)
	})
}

// UpdateManifestSha256 sets the "manifest_sha256" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateManifestSha256() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateManifestSha256()
	})
}

// ClearManifestSha256 clears the value of the "manifest_sha256" field.
func (u *PromptRequestEventUpsertBulk) ClearManifestSha256() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.ClearManifestSha256()
	})
}

// SetApplied sets the "applied" field.
func (u *PromptRequestEventUpsertBulk) SetApplied(v bool) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetApplied(v)
	})
}

// UpdateApplied sets the "applied" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateApplied() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateApplied()
	})
}

// SetReason sets the "reason" field.
func (u *PromptRequestEventUpsertBulk) SetReason(v string) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateReason() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateReason()
	})
}

// SetAddedBytes sets the "added_bytes" field.
func (u *PromptRequestEventUpsertBulk) SetAddedBytes(v int) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetAddedBytes(v)
	})
}

// AddAddedBytes adds v to the "added_bytes" field.
func (u *PromptRequestEventUpsertBulk) AddAddedBytes(v int) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddAddedBytes(v)
	})
}

// UpdateAddedBytes sets the "added_bytes" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateAddedBytes() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateAddedBytes()
	})
}

// SetApplyDurationMs sets the "apply_duration_ms" field.
func (u *PromptRequestEventUpsertBulk) SetApplyDurationMs(v int) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.SetApplyDurationMs(v)
	})
}

// AddApplyDurationMs adds v to the "apply_duration_ms" field.
func (u *PromptRequestEventUpsertBulk) AddApplyDurationMs(v int) *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.AddApplyDurationMs(v)
	})
}

// UpdateApplyDurationMs sets the "apply_duration_ms" field to the value that was provided on create.
func (u *PromptRequestEventUpsertBulk) UpdateApplyDurationMs() *PromptRequestEventUpsertBulk {
	return u.Update(func(s *PromptRequestEventUpsert) {
		s.UpdateApplyDurationMs()
	})
}

// Exec executes the query.
func (u *PromptRequestEventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromptRequestEventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptRequestEventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptRequestEventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
