// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/prompttemplatedraft"
)

// PromptTemplateDraftUpdate is the builder for updating PromptTemplateDraft entities.
type PromptTemplateDraftUpdate struct {
	config
	hooks    []Hook
	mutation *PromptTemplateDraftMutation
}

// Where appends a list predicates to the PromptTemplateDraftUpdate builder.
func (_u *PromptTemplateDraftUpdate) Where(ps ...predicate.PromptTemplateDraft) *PromptTemplateDraftUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptTemplateDraftUpdate) SetUpdatedAt(v time.Time) *PromptTemplateDraftUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *PromptTemplateDraftUpdate) SetTemplateID(v int64) *PromptTemplateDraftUpdate {
	_u.mutation.ResetTemplateID()
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdate) SetNillableTemplateID(v *int64) *PromptTemplateDraftUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// AddTemplateID adds value to the "template_id" field.
func (_u *PromptTemplateDraftUpdate) AddTemplateID(v int64) *PromptTemplateDraftUpdate {
	_u.mutation.AddTemplateID(v)
	return _u
}

// SetBody sets the "body" field.
func (_u *PromptTemplateDraftUpdate) SetBody(v string) *PromptTemplateDraftUpdate {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdate) SetNillableBody(v *string) *PromptTemplateDraftUpdate {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetClientModels sets the "client_models" field.
func (_u *PromptTemplateDraftUpdate) SetClientModels(v []string) *PromptTemplateDraftUpdate {
	_u.mutation.SetClientModels(v)
	return _u
}

// AppendClientModels appends value to the "client_models" field.
func (_u *PromptTemplateDraftUpdate) AppendClientModels(v []string) *PromptTemplateDraftUpdate {
	_u.mutation.AppendClientModels(v)
	return _u
}

// SetUpstreamModels sets the "upstream_models" field.
func (_u *PromptTemplateDraftUpdate) SetUpstreamModels(v []string) *PromptTemplateDraftUpdate {
	_u.mutation.SetUpstreamModels(v)
	return _u
}

// AppendUpstreamModels appends value to the "upstream_models" field.
func (_u *PromptTemplateDraftUpdate) AppendUpstreamModels(v []string) *PromptTemplateDraftUpdate {
	_u.mutation.AppendUpstreamModels(v)
	return _u
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (_u *PromptTemplateDraftUpdate) SetSupportedProfiles(v []string) *PromptTemplateDraftUpdate {
	_u.mutation.SetSupportedProfiles(v)
	return _u
}

// AppendSupportedProfiles appends value to the "supported_profiles" field.
func (_u *PromptTemplateDraftUpdate) AppendSupportedProfiles(v []string) *PromptTemplateDraftUpdate {
	_u.mutation.AppendSupportedProfiles(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *PromptTemplateDraftUpdate) SetRevision(v int) *PromptTemplateDraftUpdate {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdate) SetNillableRevision(v *int) *PromptTemplateDraftUpdate {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *PromptTemplateDraftUpdate) AddRevision(v int) *PromptTemplateDraftUpdate {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PromptTemplateDraftUpdate) SetUpdatedBy(v int64) *PromptTemplateDraftUpdate {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdate) SetNillableUpdatedBy(v *int64) *PromptTemplateDraftUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PromptTemplateDraftUpdate) AddUpdatedBy(v int64) *PromptTemplateDraftUpdate {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PromptTemplateDraftUpdate) ClearUpdatedBy() *PromptTemplateDraftUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the PromptTemplateDraftMutation object of the builder.
func (_u *PromptTemplateDraftUpdate) Mutation() *PromptTemplateDraftMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PromptTemplateDraftUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptTemplateDraftUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PromptTemplateDraftUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptTemplateDraftUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptTemplateDraftUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prompttemplatedraft.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptTemplateDraftUpdate) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := prompttemplatedraft.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateDraft.body": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptTemplateDraftUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prompttemplatedraft.Table, prompttemplatedraft.Columns, sqlgraph.NewFieldSpec(prompttemplatedraft.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(prompttemplatedraft.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTemplateID(); ok {
		_spec.AddField(prompttemplatedraft.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(prompttemplatedraft.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientModels(); ok {
		_spec.SetField(prompttemplatedraft.FieldClientModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClientModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplatedraft.FieldClientModels, value)
		})
	}
	if value, ok := _u.mutation.UpstreamModels(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpstreamModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplatedraft.FieldUpstreamModels, value)
		})
	}
	if value, ok := _u.mutation.SupportedProfiles(); ok {
		_spec.SetField(prompttemplatedraft.FieldSupportedProfiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedProfiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplatedraft.FieldSupportedProfiles, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(prompttemplatedraft.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(prompttemplatedraft.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(prompttemplatedraft.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(prompttemplatedraft.FieldUpdatedBy, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prompttemplatedraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PromptTemplateDraftUpdateOne is the builder for updating a single PromptTemplateDraft entity.
type PromptTemplateDraftUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PromptTemplateDraftMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PromptTemplateDraftUpdateOne) SetUpdatedAt(v time.Time) *PromptTemplateDraftUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *PromptTemplateDraftUpdateOne) SetTemplateID(v int64) *PromptTemplateDraftUpdateOne {
	_u.mutation.ResetTemplateID()
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdateOne) SetNillableTemplateID(v *int64) *PromptTemplateDraftUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// AddTemplateID adds value to the "template_id" field.
func (_u *PromptTemplateDraftUpdateOne) AddTemplateID(v int64) *PromptTemplateDraftUpdateOne {
	_u.mutation.AddTemplateID(v)
	return _u
}

// SetBody sets the "body" field.
func (_u *PromptTemplateDraftUpdateOne) SetBody(v string) *PromptTemplateDraftUpdateOne {
	_u.mutation.SetBody(v)
	return _u
}

// SetNillableBody sets the "body" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdateOne) SetNillableBody(v *string) *PromptTemplateDraftUpdateOne {
	if v != nil {
		_u.SetBody(*v)
	}
	return _u
}

// SetClientModels sets the "client_models" field.
func (_u *PromptTemplateDraftUpdateOne) SetClientModels(v []string) *PromptTemplateDraftUpdateOne {
	_u.mutation.SetClientModels(v)
	return _u
}

// AppendClientModels appends value to the "client_models" field.
func (_u *PromptTemplateDraftUpdateOne) AppendClientModels(v []string) *PromptTemplateDraftUpdateOne {
	_u.mutation.AppendClientModels(v)
	return _u
}

// SetUpstreamModels sets the "upstream_models" field.
func (_u *PromptTemplateDraftUpdateOne) SetUpstreamModels(v []string) *PromptTemplateDraftUpdateOne {
	_u.mutation.SetUpstreamModels(v)
	return _u
}

// AppendUpstreamModels appends value to the "upstream_models" field.
func (_u *PromptTemplateDraftUpdateOne) AppendUpstreamModels(v []string) *PromptTemplateDraftUpdateOne {
	_u.mutation.AppendUpstreamModels(v)
	return _u
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (_u *PromptTemplateDraftUpdateOne) SetSupportedProfiles(v []string) *PromptTemplateDraftUpdateOne {
	_u.mutation.SetSupportedProfiles(v)
	return _u
}

// AppendSupportedProfiles appends value to the "supported_profiles" field.
func (_u *PromptTemplateDraftUpdateOne) AppendSupportedProfiles(v []string) *PromptTemplateDraftUpdateOne {
	_u.mutation.AppendSupportedProfiles(v)
	return _u
}

// SetRevision sets the "revision" field.
func (_u *PromptTemplateDraftUpdateOne) SetRevision(v int) *PromptTemplateDraftUpdateOne {
	_u.mutation.ResetRevision()
	_u.mutation.SetRevision(v)
	return _u
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdateOne) SetNillableRevision(v *int) *PromptTemplateDraftUpdateOne {
	if v != nil {
		_u.SetRevision(*v)
	}
	return _u
}

// AddRevision adds value to the "revision" field.
func (_u *PromptTemplateDraftUpdateOne) AddRevision(v int) *PromptTemplateDraftUpdateOne {
	_u.mutation.AddRevision(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PromptTemplateDraftUpdateOne) SetUpdatedBy(v int64) *PromptTemplateDraftUpdateOne {
	_u.mutation.ResetUpdatedBy()
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PromptTemplateDraftUpdateOne) SetNillableUpdatedBy(v *int64) *PromptTemplateDraftUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// AddUpdatedBy adds value to the "updated_by" field.
func (_u *PromptTemplateDraftUpdateOne) AddUpdatedBy(v int64) *PromptTemplateDraftUpdateOne {
	_u.mutation.AddUpdatedBy(v)
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PromptTemplateDraftUpdateOne) ClearUpdatedBy() *PromptTemplateDraftUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// Mutation returns the PromptTemplateDraftMutation object of the builder.
func (_u *PromptTemplateDraftUpdateOne) Mutation() *PromptTemplateDraftMutation {
	return _u.mutation
}

// Where appends a list predicates to the PromptTemplateDraftUpdate builder.
func (_u *PromptTemplateDraftUpdateOne) Where(ps ...predicate.PromptTemplateDraft) *PromptTemplateDraftUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PromptTemplateDraftUpdateOne) Select(field string, fields ...string) *PromptTemplateDraftUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PromptTemplateDraft entity.
func (_u *PromptTemplateDraftUpdateOne) Save(ctx context.Context) (*PromptTemplateDraft, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PromptTemplateDraftUpdateOne) SaveX(ctx context.Context) *PromptTemplateDraft {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PromptTemplateDraftUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PromptTemplateDraftUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PromptTemplateDraftUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := prompttemplatedraft.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PromptTemplateDraftUpdateOne) check() error {
	if v, ok := _u.mutation.Body(); ok {
		if err := prompttemplatedraft.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateDraft.body": %w`, err)}
		}
	}
	return nil
}

func (_u *PromptTemplateDraftUpdateOne) sqlSave(ctx context.Context) (_node *PromptTemplateDraft, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(prompttemplatedraft.Table, prompttemplatedraft.Columns, sqlgraph.NewFieldSpec(prompttemplatedraft.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PromptTemplateDraft.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, prompttemplatedraft.FieldID)
		for _, f := range fields {
			if !prompttemplatedraft.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != prompttemplatedraft.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(prompttemplatedraft.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedTemplateID(); ok {
		_spec.AddField(prompttemplatedraft.FieldTemplateID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Body(); ok {
		_spec.SetField(prompttemplatedraft.FieldBody, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientModels(); ok {
		_spec.SetField(prompttemplatedraft.FieldClientModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedClientModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplatedraft.FieldClientModels, value)
		})
	}
	if value, ok := _u.mutation.UpstreamModels(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpstreamModels, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedUpstreamModels(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplatedraft.FieldUpstreamModels, value)
		})
	}
	if value, ok := _u.mutation.SupportedProfiles(); ok {
		_spec.SetField(prompttemplatedraft.FieldSupportedProfiles, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedProfiles(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, prompttemplatedraft.FieldSupportedProfiles, value)
		})
	}
	if value, ok := _u.mutation.Revision(); ok {
		_spec.SetField(prompttemplatedraft.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRevision(); ok {
		_spec.AddField(prompttemplatedraft.FieldRevision, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpdatedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedBy(); ok {
		_spec.AddField(prompttemplatedraft.FieldUpdatedBy, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(prompttemplatedraft.FieldUpdatedBy, field.TypeInt64)
	}
	_node = &PromptTemplateDraft{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{prompttemplatedraft.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
