// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/prompttemplate"
)

// PromptTemplate is the model entity for the PromptTemplate schema.
type PromptTemplate struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 模板名称；活动模板（archived_at IS NULL）内唯一
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// 候选来源 URL，仅记录，网关不会自动下载
	SourceURL *string `json:"source_url,omitempty"`
	// 来源与适用范围说明
	SourceNote *string `json:"source_note,omitempty"`
	// 归档时间；归档后不能新增绑定，既有绑定继续运行
	ArchivedAt *time.Time `json:"archived_at,omitempty"`
	// 乐观锁版本，每次元数据更新递增
	Revision int `json:"revision,omitempty"`
	// CreatedBy holds the value of the "created_by" field.
	CreatedBy *int64 `json:"created_by,omitempty"`
	// UpdatedBy holds the value of the "updated_by" field.
	UpdatedBy    *int64 `json:"updated_by,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromptTemplate) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case prompttemplate.FieldID, prompttemplate.FieldRevision, prompttemplate.FieldCreatedBy, prompttemplate.FieldUpdatedBy:
			values[i] = new(sql.NullInt64)
		case prompttemplate.FieldName, prompttemplate.FieldDescription, prompttemplate.FieldSourceURL, prompttemplate.FieldSourceNote:
			values[i] = new(sql.NullString)
		case prompttemplate.FieldCreatedAt, prompttemplate.FieldUpdatedAt, prompttemplate.FieldArchivedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromptTemplate fields.
func (_m *PromptTemplate) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case prompttemplate.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case prompttemplate.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case prompttemplate.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case prompttemplate.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case prompttemplate.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case prompttemplate.FieldSourceURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_url", values[i])
			} else if value.Valid {
				_m.SourceURL = new(string)
				*_m.SourceURL = value.String
			}
		case prompttemplate.FieldSourceNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_note", values[i])
			} else if value.Valid {
				_m.SourceNote = new(string)
				*_m.SourceNote = value.String
			}
		case prompttemplate.FieldArchivedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field archived_at", values[i])
			} else if value.Valid {
				_m.ArchivedAt = new(time.Time)
				*_m.ArchivedAt = value.Time
			}
		case prompttemplate.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = int(value.Int64)
			}
		case prompttemplate.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = new(int64)
				*_m.CreatedBy = value.Int64
			}
		case prompttemplate.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = new(int64)
				*_m.UpdatedBy = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromptTemplate.
// This includes values selected through modifiers, order, etc.
func (_m *PromptTemplate) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PromptTemplate.
// Note that you need to call PromptTemplate.Unwrap() before calling this method if this PromptTemplate
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromptTemplate) Update() *PromptTemplateUpdateOne {
	return NewPromptTemplateClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromptTemplate entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromptTemplate) Unwrap() *PromptTemplate {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromptTemplate is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromptTemplate) String() string {
	var builder strings.Builder
	builder.WriteString("PromptTemplate(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SourceURL; v != nil {
		builder.WriteString("source_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SourceNote; v != nil {
		builder.WriteString("source_note=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ArchivedAt; v != nil {
		builder.WriteString("archived_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	if v := _m.CreatedBy; v != nil {
		builder.WriteString("created_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedBy; v != nil {
		builder.WriteString("updated_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PromptTemplates is a parsable slice of PromptTemplate.
type PromptTemplates []*PromptTemplate
