// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/promptadminevent"
)

// PromptAdminEvent is the model entity for the PromptAdminEvent schema.
type PromptAdminEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// create/update_draft/publish/archive/bind/unbind/set_override/clear_override 等
	Action string `json:"action,omitempty"`
	// Scope holds the value of the "scope" field.
	Scope string `json:"scope,omitempty"`
	// TemplateID holds the value of the "template_id" field.
	TemplateID *int64 `json:"template_id,omitempty"`
	// VersionID holds the value of the "version_id" field.
	VersionID *int64 `json:"version_id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *int64 `json:"group_id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID *int64 `json:"account_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID *int64 `json:"actor_id,omitempty"`
	// ActorName holds the value of the "actor_name" field.
	ActorName *string `json:"actor_name,omitempty"`
	// BeforeState holds the value of the "before_state" field.
	BeforeState map[string]interface{} `json:"before_state,omitempty"`
	// AfterState holds the value of the "after_state" field.
	AfterState map[string]interface{} `json:"after_state,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID *string `json:"request_id,omitempty"`
	// Note holds the value of the "note" field.
	Note         *string `json:"note,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PromptAdminEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case promptadminevent.FieldBeforeState, promptadminevent.FieldAfterState:
			values[i] = new([]byte)
		case promptadminevent.FieldID, promptadminevent.FieldTemplateID, promptadminevent.FieldVersionID, promptadminevent.FieldGroupID, promptadminevent.FieldAccountID, promptadminevent.FieldActorID:
			values[i] = new(sql.NullInt64)
		case promptadminevent.FieldAction, promptadminevent.FieldScope, promptadminevent.FieldActorName, promptadminevent.FieldRequestID, promptadminevent.FieldNote:
			values[i] = new(sql.NullString)
		case promptadminevent.FieldCreatedAt, promptadminevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PromptAdminEvent fields.
func (_m *PromptAdminEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case promptadminevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case promptadminevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case promptadminevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case promptadminevent.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case promptadminevent.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case promptadminevent.FieldTemplateID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field template_id", values[i])
			} else if value.Valid {
				_m.TemplateID = new(int64)
				*_m.TemplateID = value.Int64
			}
		case promptadminevent.FieldVersionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version_id", values[i])
			} else if value.Valid {
				_m.VersionID = new(int64)
				*_m.VersionID = value.Int64
			}
		case promptadminevent.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(int64)
				*_m.GroupID = value.Int64
			}
		case promptadminevent.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = new(int64)
				*_m.AccountID = value.Int64
			}
		case promptadminevent.FieldActorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = new(int64)
				*_m.ActorID = value.Int64
			}
		case promptadminevent.FieldActorName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actor_name", values[i])
			} else if value.Valid {
				_m.ActorName = new(string)
				*_m.ActorName = value.String
			}
		case promptadminevent.FieldBeforeState:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field before_state", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.BeforeState); err != nil {
					return fmt.Errorf("unmarshal field before_state: %w", err)
				}
			}
		case promptadminevent.FieldAfterState:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field after_state", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AfterState); err != nil {
					return fmt.Errorf("unmarshal field after_state: %w", err)
				}
			}
		case promptadminevent.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = new(string)
				*_m.RequestID = value.String
			}
		case promptadminevent.FieldNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field note", values[i])
			} else if value.Valid {
				_m.Note = new(string)
				*_m.Note = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PromptAdminEvent.
// This includes values selected through modifiers, order, etc.
func (_m *PromptAdminEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PromptAdminEvent.
// Note that you need to call PromptAdminEvent.Unwrap() before calling this method if this PromptAdminEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PromptAdminEvent) Update() *PromptAdminEventUpdateOne {
	return NewPromptAdminEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PromptAdminEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PromptAdminEvent) Unwrap() *PromptAdminEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PromptAdminEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PromptAdminEvent) String() string {
	var builder strings.Builder
	builder.WriteString("PromptAdminEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	if v := _m.TemplateID; v != nil {
		builder.WriteString("template_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.VersionID; v != nil {
		builder.WriteString("version_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.AccountID; v != nil {
		builder.WriteString("account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActorID; v != nil {
		builder.WriteString("actor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ActorName; v != nil {
		builder.WriteString("actor_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("before_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.BeforeState))
	builder.WriteString(", ")
	builder.WriteString("after_state=")
	builder.WriteString(fmt.Sprintf("%v", _m.AfterState))
	builder.WriteString(", ")
	if v := _m.RequestID; v != nil {
		builder.WriteString("request_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Note; v != nil {
		builder.WriteString("note=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// PromptAdminEvents is a parsable slice of PromptAdminEvent.
type PromptAdminEvents []*PromptAdminEvent
