// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/prompttemplatedraft"
)

// PromptTemplateDraftCreate is the builder for creating a PromptTemplateDraft entity.
type PromptTemplateDraftCreate struct {
	config
	mutation *PromptTemplateDraftMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PromptTemplateDraftCreate) SetCreatedAt(v time.Time) *PromptTemplateDraftCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PromptTemplateDraftCreate) SetNillableCreatedAt(v *time.Time) *PromptTemplateDraftCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PromptTemplateDraftCreate) SetUpdatedAt(v time.Time) *PromptTemplateDraftCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PromptTemplateDraftCreate) SetNillableUpdatedAt(v *time.Time) *PromptTemplateDraftCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *PromptTemplateDraftCreate) SetTemplateID(v int64) *PromptTemplateDraftCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetBody sets the "body" field.
func (_c *PromptTemplateDraftCreate) SetBody(v string) *PromptTemplateDraftCreate {
	_c.mutation.SetBody(v)
	return _c
}

// SetClientModels sets the "client_models" field.
func (_c *PromptTemplateDraftCreate) SetClientModels(v []string) *PromptTemplateDraftCreate {
	_c.mutation.SetClientModels(v)
	return _c
}

// SetUpstreamModels sets the "upstream_models" field.
func (_c *PromptTemplateDraftCreate) SetUpstreamModels(v []string) *PromptTemplateDraftCreate {
	_c.mutation.SetUpstreamModels(v)
	return _c
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (_c *PromptTemplateDraftCreate) SetSupportedProfiles(v []string) *PromptTemplateDraftCreate {
	_c.mutation.SetSupportedProfiles(v)
	return _c
}

// SetRevision sets the "revision" field.
func (_c *PromptTemplateDraftCreate) SetRevision(v int) *PromptTemplateDraftCreate {
	_c.mutation.SetRevision(v)
	return _c
}

// SetNillableRevision sets the "revision" field if the given value is not nil.
func (_c *PromptTemplateDraftCreate) SetNillableRevision(v *int) *PromptTemplateDraftCreate {
	if v != nil {
		_c.SetRevision(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *PromptTemplateDraftCreate) SetUpdatedBy(v int64) *PromptTemplateDraftCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *PromptTemplateDraftCreate) SetNillableUpdatedBy(v *int64) *PromptTemplateDraftCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// Mutation returns the PromptTemplateDraftMutation object of the builder.
func (_c *PromptTemplateDraftCreate) Mutation() *PromptTemplateDraftMutation {
	return _c.mutation
}

// Save creates the PromptTemplateDraft in the database.
func (_c *PromptTemplateDraftCreate) Save(ctx context.Context) (*PromptTemplateDraft, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PromptTemplateDraftCreate) SaveX(ctx context.Context) *PromptTemplateDraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateDraftCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateDraftCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PromptTemplateDraftCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := prompttemplatedraft.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := prompttemplatedraft.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ClientModels(); !ok {
		v := prompttemplatedraft.DefaultClientModels()
		_c.mutation.SetClientModels(v)
	}
	if _, ok := _c.mutation.UpstreamModels(); !ok {
		v := prompttemplatedraft.DefaultUpstreamModels()
		_c.mutation.SetUpstreamModels(v)
	}
	if _, ok := _c.mutation.SupportedProfiles(); !ok {
		v := prompttemplatedraft.DefaultSupportedProfiles()
		_c.mutation.SetSupportedProfiles(v)
	}
	if _, ok := _c.mutation.Revision(); !ok {
		v := prompttemplatedraft.DefaultRevision
		_c.mutation.SetRevision(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PromptTemplateDraftCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PromptTemplateDraft.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PromptTemplateDraft.updated_at"`)}
	}
	if _, ok := _c.mutation.TemplateID(); !ok {
		return &ValidationError{Name: "template_id", err: errors.New(`ent: missing required field "PromptTemplateDraft.template_id"`)}
	}
	if _, ok := _c.mutation.Body(); !ok {
		return &ValidationError{Name: "body", err: errors.New(`ent: missing required field "PromptTemplateDraft.body"`)}
	}
	if v, ok := _c.mutation.Body(); ok {
		if err := prompttemplatedraft.BodyValidator(v); err != nil {
			return &ValidationError{Name: "body", err: fmt.Errorf(`ent: validator failed for field "PromptTemplateDraft.body": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientModels(); !ok {
		return &ValidationError{Name: "client_models", err: errors.New(`ent: missing required field "PromptTemplateDraft.client_models"`)}
	}
	if _, ok := _c.mutation.UpstreamModels(); !ok {
		return &ValidationError{Name: "upstream_models", err: errors.New(`ent: missing required field "PromptTemplateDraft.upstream_models"`)}
	}
	if _, ok := _c.mutation.SupportedProfiles(); !ok {
		return &ValidationError{Name: "supported_profiles", err: errors.New(`ent: missing required field "PromptTemplateDraft.supported_profiles"`)}
	}
	if _, ok := _c.mutation.Revision(); !ok {
		return &ValidationError{Name: "revision", err: errors.New(`ent: missing required field "PromptTemplateDraft.revision"`)}
	}
	return nil
}

func (_c *PromptTemplateDraftCreate) sqlSave(ctx context.Context) (*PromptTemplateDraft, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PromptTemplateDraftCreate) createSpec() (*PromptTemplateDraft, *sqlgraph.CreateSpec) {
	var (
		_node = &PromptTemplateDraft{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(prompttemplatedraft.Table, sqlgraph.NewFieldSpec(prompttemplatedraft.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(prompttemplatedraft.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(prompttemplatedraft.FieldTemplateID, field.TypeInt64, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.Body(); ok {
		_spec.SetField(prompttemplatedraft.FieldBody, field.TypeString, value)
		_node.Body = value
	}
	if value, ok := _c.mutation.ClientModels(); ok {
		_spec.SetField(prompttemplatedraft.FieldClientModels, field.TypeJSON, value)
		_node.ClientModels = value
	}
	if value, ok := _c.mutation.UpstreamModels(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpstreamModels, field.TypeJSON, value)
		_node.UpstreamModels = value
	}
	if value, ok := _c.mutation.SupportedProfiles(); ok {
		_spec.SetField(prompttemplatedraft.FieldSupportedProfiles, field.TypeJSON, value)
		_node.SupportedProfiles = value
	}
	if value, ok := _c.mutation.Revision(); ok {
		_spec.SetField(prompttemplatedraft.FieldRevision, field.TypeInt, value)
		_node.Revision = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(prompttemplatedraft.FieldUpdatedBy, field.TypeInt64, value)
		_node.UpdatedBy = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptTemplateDraft.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptTemplateDraftUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptTemplateDraftCreate) OnConflict(opts ...sql.ConflictOption) *PromptTemplateDraftUpsertOne {
	_c.conflict = opts
	return &PromptTemplateDraftUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptTemplateDraft.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptTemplateDraftCreate) OnConflictColumns(columns ...string) *PromptTemplateDraftUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptTemplateDraftUpsertOne{
		create: _c,
	}
}

type (
	// PromptTemplateDraftUpsertOne is the builder for "upsert"-ing
	//  one PromptTemplateDraft node.
	PromptTemplateDraftUpsertOne struct {
		create *PromptTemplateDraftCreate
	}

	// PromptTemplateDraftUpsert is the "OnConflict" setter.
	PromptTemplateDraftUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptTemplateDraftUpsert) SetUpdatedAt(v time.Time) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateUpdatedAt() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldUpdatedAt)
	return u
}

// SetTemplateID sets the "template_id" field.
func (u *PromptTemplateDraftUpsert) SetTemplateID(v int64) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldTemplateID, v)
	return u
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateTemplateID() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldTemplateID)
	return u
}

// AddTemplateID adds v to the "template_id" field.
func (u *PromptTemplateDraftUpsert) AddTemplateID(v int64) *PromptTemplateDraftUpsert {
	u.Add(prompttemplatedraft.FieldTemplateID, v)
	return u
}

// SetBody sets the "body" field.
func (u *PromptTemplateDraftUpsert) SetBody(v string) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldBody, v)
	return u
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateBody() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldBody)
	return u
}

// SetClientModels sets the "client_models" field.
func (u *PromptTemplateDraftUpsert) SetClientModels(v []string) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldClientModels, v)
	return u
}

// UpdateClientModels sets the "client_models" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateClientModels() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldClientModels)
	return u
}

// SetUpstreamModels sets the "upstream_models" field.
func (u *PromptTemplateDraftUpsert) SetUpstreamModels(v []string) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldUpstreamModels, v)
	return u
}

// UpdateUpstreamModels sets the "upstream_models" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateUpstreamModels() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldUpstreamModels)
	return u
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (u *PromptTemplateDraftUpsert) SetSupportedProfiles(v []string) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldSupportedProfiles, v)
	return u
}

// UpdateSupportedProfiles sets the "supported_profiles" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateSupportedProfiles() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldSupportedProfiles)
	return u
}

// SetRevision sets the "revision" field.
func (u *PromptTemplateDraftUpsert) SetRevision(v int) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldRevision, v)
	return u
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateRevision() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldRevision)
	return u
}

// AddRevision adds v to the "revision" field.
func (u *PromptTemplateDraftUpsert) AddRevision(v int) *PromptTemplateDraftUpsert {
	u.Add(prompttemplatedraft.FieldRevision, v)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PromptTemplateDraftUpsert) SetUpdatedBy(v int64) *PromptTemplateDraftUpsert {
	u.Set(prompttemplatedraft.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsert) UpdateUpdatedBy() *PromptTemplateDraftUpsert {
	u.SetExcluded(prompttemplatedraft.FieldUpdatedBy)
	return u
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PromptTemplateDraftUpsert) AddUpdatedBy(v int64) *PromptTemplateDraftUpsert {
	u.Add(prompttemplatedraft.FieldUpdatedBy, v)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PromptTemplateDraftUpsert) ClearUpdatedBy() *PromptTemplateDraftUpsert {
	u.SetNull(prompttemplatedraft.FieldUpdatedBy)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PromptTemplateDraft.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptTemplateDraftUpsertOne) UpdateNewValues() *PromptTemplateDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(prompttemplatedraft.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptTemplateDraft.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PromptTemplateDraftUpsertOne) Ignore() *PromptTemplateDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptTemplateDraftUpsertOne) DoNothing() *PromptTemplateDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptTemplateDraftCreate.OnConflict
// documentation for more info.
func (u *PromptTemplateDraftUpsertOne) Update(set func(*PromptTemplateDraftUpsert)) *PromptTemplateDraftUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptTemplateDraftUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptTemplateDraftUpsertOne) SetUpdatedAt(v time.Time) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateUpdatedAt() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *PromptTemplateDraftUpsertOne) SetTemplateID(v int64) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *PromptTemplateDraftUpsertOne) AddTemplateID(v int64) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateTemplateID() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateTemplateID()
	})
}

// SetBody sets the "body" field.
func (u *PromptTemplateDraftUpsertOne) SetBody(v string) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateBody() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateBody()
	})
}

// SetClientModels sets the "client_models" field.
func (u *PromptTemplateDraftUpsertOne) SetClientModels(v []string) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetClientModels(v)
	})
}

// UpdateClientModels sets the "client_models" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateClientModels() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateClientModels()
	})
}

// SetUpstreamModels sets the "upstream_models" field.
func (u *PromptTemplateDraftUpsertOne) SetUpstreamModels(v []string) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetUpstreamModels(v)
	})
}

// UpdateUpstreamModels sets the "upstream_models" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateUpstreamModels() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateUpstreamModels()
	})
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (u *PromptTemplateDraftUpsertOne) SetSupportedProfiles(v []string) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetSupportedProfiles(v)
	})
}

// UpdateSupportedProfiles sets the "supported_profiles" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateSupportedProfiles() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateSupportedProfiles()
	})
}

// SetRevision sets the "revision" field.
func (u *PromptTemplateDraftUpsertOne) SetRevision(v int) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *PromptTemplateDraftUpsertOne) AddRevision(v int) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateRevision() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PromptTemplateDraftUpsertOne) SetUpdatedBy(v int64) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PromptTemplateDraftUpsertOne) AddUpdatedBy(v int64) *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertOne) UpdateUpdatedBy() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PromptTemplateDraftUpsertOne) ClearUpdatedBy() *PromptTemplateDraftUpsertOne {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *PromptTemplateDraftUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptTemplateDraftCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptTemplateDraftUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PromptTemplateDraftUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PromptTemplateDraftUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PromptTemplateDraftCreateBulk is the builder for creating many PromptTemplateDraft entities in bulk.
type PromptTemplateDraftCreateBulk struct {
	config
	err      error
	builders []*PromptTemplateDraftCreate
	conflict []sql.ConflictOption
}

// Save creates the PromptTemplateDraft entities in the database.
func (_c *PromptTemplateDraftCreateBulk) Save(ctx context.Context) ([]*PromptTemplateDraft, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PromptTemplateDraft, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PromptTemplateDraftMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PromptTemplateDraftCreateBulk) SaveX(ctx context.Context) []*PromptTemplateDraft {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PromptTemplateDraftCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PromptTemplateDraftCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PromptTemplateDraft.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PromptTemplateDraftUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PromptTemplateDraftCreateBulk) OnConflict(opts ...sql.ConflictOption) *PromptTemplateDraftUpsertBulk {
	_c.conflict = opts
	return &PromptTemplateDraftUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PromptTemplateDraft.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PromptTemplateDraftCreateBulk) OnConflictColumns(columns ...string) *PromptTemplateDraftUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PromptTemplateDraftUpsertBulk{
		create: _c,
	}
}

// PromptTemplateDraftUpsertBulk is the builder for "upsert"-ing
// a bulk of PromptTemplateDraft nodes.
type PromptTemplateDraftUpsertBulk struct {
	create *PromptTemplateDraftCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PromptTemplateDraft.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PromptTemplateDraftUpsertBulk) UpdateNewValues() *PromptTemplateDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(prompttemplatedraft.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PromptTemplateDraft.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PromptTemplateDraftUpsertBulk) Ignore() *PromptTemplateDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PromptTemplateDraftUpsertBulk) DoNothing() *PromptTemplateDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PromptTemplateDraftCreateBulk.OnConflict
// documentation for more info.
func (u *PromptTemplateDraftUpsertBulk) Update(set func(*PromptTemplateDraftUpsert)) *PromptTemplateDraftUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PromptTemplateDraftUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PromptTemplateDraftUpsertBulk) SetUpdatedAt(v time.Time) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateUpdatedAt() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetTemplateID sets the "template_id" field.
func (u *PromptTemplateDraftUpsertBulk) SetTemplateID(v int64) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetTemplateID(v)
	})
}

// AddTemplateID adds v to the "template_id" field.
func (u *PromptTemplateDraftUpsertBulk) AddTemplateID(v int64) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.AddTemplateID(v)
	})
}

// UpdateTemplateID sets the "template_id" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateTemplateID() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateTemplateID()
	})
}

// SetBody sets the "body" field.
func (u *PromptTemplateDraftUpsertBulk) SetBody(v string) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetBody(v)
	})
}

// UpdateBody sets the "body" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateBody() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateBody()
	})
}

// SetClientModels sets the "client_models" field.
func (u *PromptTemplateDraftUpsertBulk) SetClientModels(v []string) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetClientModels(v)
	})
}

// UpdateClientModels sets the "client_models" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateClientModels() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateClientModels()
	})
}

// SetUpstreamModels sets the "upstream_models" field.
func (u *PromptTemplateDraftUpsertBulk) SetUpstreamModels(v []string) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetUpstreamModels(v)
	})
}

// UpdateUpstreamModels sets the "upstream_models" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateUpstreamModels() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateUpstreamModels()
	})
}

// SetSupportedProfiles sets the "supported_profiles" field.
func (u *PromptTemplateDraftUpsertBulk) SetSupportedProfiles(v []string) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetSupportedProfiles(v)
	})
}

// UpdateSupportedProfiles sets the "supported_profiles" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateSupportedProfiles() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateSupportedProfiles()
	})
}

// SetRevision sets the "revision" field.
func (u *PromptTemplateDraftUpsertBulk) SetRevision(v int) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetRevision(v)
	})
}

// AddRevision adds v to the "revision" field.
func (u *PromptTemplateDraftUpsertBulk) AddRevision(v int) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.AddRevision(v)
	})
}

// UpdateRevision sets the "revision" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateRevision() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateRevision()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *PromptTemplateDraftUpsertBulk) SetUpdatedBy(v int64) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.SetUpdatedBy(v)
	})
}

// AddUpdatedBy adds v to the "updated_by" field.
func (u *PromptTemplateDraftUpsertBulk) AddUpdatedBy(v int64) *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.AddUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *PromptTemplateDraftUpsertBulk) UpdateUpdatedBy() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *PromptTemplateDraftUpsertBulk) ClearUpdatedBy() *PromptTemplateDraftUpsertBulk {
	return u.Update(func(s *PromptTemplateDraftUpsert) {
		s.ClearUpdatedBy()
	})
}

// Exec executes the query.
func (u *PromptTemplateDraftUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PromptTemplateDraftCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PromptTemplateDraftCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PromptTemplateDraftUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
