// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/studentverification"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// StudentVerificationCreate is the builder for creating a StudentVerification entity.
type StudentVerificationCreate struct {
	config
	mutation *StudentVerificationMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *StudentVerificationCreate) SetCreatedAt(v time.Time) *StudentVerificationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableCreatedAt(v *time.Time) *StudentVerificationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *StudentVerificationCreate) SetUpdatedAt(v time.Time) *StudentVerificationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableUpdatedAt(v *time.Time) *StudentVerificationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *StudentVerificationCreate) SetUserID(v int64) *StudentVerificationCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableUserID(v *int64) *StudentVerificationCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *StudentVerificationCreate) SetEmail(v string) *StudentVerificationCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetEmailRaw sets the "email_raw" field.
func (_c *StudentVerificationCreate) SetEmailRaw(v string) *StudentVerificationCreate {
	_c.mutation.SetEmailRaw(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *StudentVerificationCreate) SetStatus(v string) *StudentVerificationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableStatus(v *string) *StudentVerificationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *StudentVerificationCreate) SetVerifiedAt(v time.Time) *StudentVerificationCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetExpiresAt sets the "expires_at" field.
func (_c *StudentVerificationCreate) SetExpiresAt(v time.Time) *StudentVerificationCreate {
	_c.mutation.SetExpiresAt(v)
	return _c
}

// SetRevokedAt sets the "revoked_at" field.
func (_c *StudentVerificationCreate) SetRevokedAt(v time.Time) *StudentVerificationCreate {
	_c.mutation.SetRevokedAt(v)
	return _c
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableRevokedAt(v *time.Time) *StudentVerificationCreate {
	if v != nil {
		_c.SetRevokedAt(*v)
	}
	return _c
}

// SetRevokedBy sets the "revoked_by" field.
func (_c *StudentVerificationCreate) SetRevokedBy(v int64) *StudentVerificationCreate {
	_c.mutation.SetRevokedBy(v)
	return _c
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableRevokedBy(v *int64) *StudentVerificationCreate {
	if v != nil {
		_c.SetRevokedBy(*v)
	}
	return _c
}

// SetRevokeReason sets the "revoke_reason" field.
func (_c *StudentVerificationCreate) SetRevokeReason(v string) *StudentVerificationCreate {
	_c.mutation.SetRevokeReason(v)
	return _c
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableRevokeReason(v *string) *StudentVerificationCreate {
	if v != nil {
		_c.SetRevokeReason(*v)
	}
	return _c
}

// SetRebateRateApplied sets the "rebate_rate_applied" field.
func (_c *StudentVerificationCreate) SetRebateRateApplied(v float64) *StudentVerificationCreate {
	_c.mutation.SetRebateRateApplied(v)
	return _c
}

// SetNillableRebateRateApplied sets the "rebate_rate_applied" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillableRebateRateApplied(v *float64) *StudentVerificationCreate {
	if v != nil {
		_c.SetRebateRateApplied(*v)
	}
	return _c
}

// SetPreviousRebateRate sets the "previous_rebate_rate" field.
func (_c *StudentVerificationCreate) SetPreviousRebateRate(v float64) *StudentVerificationCreate {
	_c.mutation.SetPreviousRebateRate(v)
	return _c
}

// SetNillablePreviousRebateRate sets the "previous_rebate_rate" field if the given value is not nil.
func (_c *StudentVerificationCreate) SetNillablePreviousRebateRate(v *float64) *StudentVerificationCreate {
	if v != nil {
		_c.SetPreviousRebateRate(*v)
	}
	return _c
}

// SetGrantedGroupIds sets the "granted_group_ids" field.
func (_c *StudentVerificationCreate) SetGrantedGroupIds(v []int64) *StudentVerificationCreate {
	_c.mutation.SetGrantedGroupIds(v)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *StudentVerificationCreate) SetUser(v *User) *StudentVerificationCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the StudentVerificationMutation object of the builder.
func (_c *StudentVerificationCreate) Mutation() *StudentVerificationMutation {
	return _c.mutation
}

// Save creates the StudentVerification in the database.
func (_c *StudentVerificationCreate) Save(ctx context.Context) (*StudentVerification, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StudentVerificationCreate) SaveX(ctx context.Context) *StudentVerification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudentVerificationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudentVerificationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StudentVerificationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := studentverification.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := studentverification.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := studentverification.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.GrantedGroupIds(); !ok {
		v := studentverification.DefaultGrantedGroupIds()
		_c.mutation.SetGrantedGroupIds(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StudentVerificationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StudentVerification.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "StudentVerification.updated_at"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "StudentVerification.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := studentverification.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EmailRaw(); !ok {
		return &ValidationError{Name: "email_raw", err: errors.New(`ent: missing required field "StudentVerification.email_raw"`)}
	}
	if v, ok := _c.mutation.EmailRaw(); ok {
		if err := studentverification.EmailRawValidator(v); err != nil {
			return &ValidationError{Name: "email_raw", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.email_raw": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StudentVerification.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := studentverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.VerifiedAt(); !ok {
		return &ValidationError{Name: "verified_at", err: errors.New(`ent: missing required field "StudentVerification.verified_at"`)}
	}
	if _, ok := _c.mutation.ExpiresAt(); !ok {
		return &ValidationError{Name: "expires_at", err: errors.New(`ent: missing required field "StudentVerification.expires_at"`)}
	}
	if _, ok := _c.mutation.GrantedGroupIds(); !ok {
		return &ValidationError{Name: "granted_group_ids", err: errors.New(`ent: missing required field "StudentVerification.granted_group_ids"`)}
	}
	return nil
}

func (_c *StudentVerificationCreate) sqlSave(ctx context.Context) (*StudentVerification, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StudentVerificationCreate) createSpec() (*StudentVerification, *sqlgraph.CreateSpec) {
	var (
		_node = &StudentVerification{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(studentverification.Table, sqlgraph.NewFieldSpec(studentverification.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(studentverification.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(studentverification.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(studentverification.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.EmailRaw(); ok {
		_spec.SetField(studentverification.FieldEmailRaw, field.TypeString, value)
		_node.EmailRaw = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(studentverification.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(studentverification.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = value
	}
	if value, ok := _c.mutation.ExpiresAt(); ok {
		_spec.SetField(studentverification.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if value, ok := _c.mutation.RevokedAt(); ok {
		_spec.SetField(studentverification.FieldRevokedAt, field.TypeTime, value)
		_node.RevokedAt = &value
	}
	if value, ok := _c.mutation.RevokedBy(); ok {
		_spec.SetField(studentverification.FieldRevokedBy, field.TypeInt64, value)
		_node.RevokedBy = &value
	}
	if value, ok := _c.mutation.RevokeReason(); ok {
		_spec.SetField(studentverification.FieldRevokeReason, field.TypeString, value)
		_node.RevokeReason = &value
	}
	if value, ok := _c.mutation.RebateRateApplied(); ok {
		_spec.SetField(studentverification.FieldRebateRateApplied, field.TypeFloat64, value)
		_node.RebateRateApplied = &value
	}
	if value, ok := _c.mutation.PreviousRebateRate(); ok {
		_spec.SetField(studentverification.FieldPreviousRebateRate, field.TypeFloat64, value)
		_node.PreviousRebateRate = &value
	}
	if value, ok := _c.mutation.GrantedGroupIds(); ok {
		_spec.SetField(studentverification.FieldGrantedGroupIds, field.TypeJSON, value)
		_node.GrantedGroupIds = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   studentverification.UserTable,
			Columns: []string{studentverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StudentVerification.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudentVerificationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *StudentVerificationCreate) OnConflict(opts ...sql.ConflictOption) *StudentVerificationUpsertOne {
	_c.conflict = opts
	return &StudentVerificationUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StudentVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StudentVerificationCreate) OnConflictColumns(columns ...string) *StudentVerificationUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StudentVerificationUpsertOne{
		create: _c,
	}
}

type (
	// StudentVerificationUpsertOne is the builder for "upsert"-ing
	//  one StudentVerification node.
	StudentVerificationUpsertOne struct {
		create *StudentVerificationCreate
	}

	// StudentVerificationUpsert is the "OnConflict" setter.
	StudentVerificationUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *StudentVerificationUpsert) SetUpdatedAt(v time.Time) *StudentVerificationUpsert {
	u.Set(studentverification.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateUpdatedAt() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *StudentVerificationUpsert) SetUserID(v int64) *StudentVerificationUpsert {
	u.Set(studentverification.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateUserID() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldUserID)
	return u
}

// ClearUserID clears the value of the "user_id" field.
func (u *StudentVerificationUpsert) ClearUserID() *StudentVerificationUpsert {
	u.SetNull(studentverification.FieldUserID)
	return u
}

// SetEmail sets the "email" field.
func (u *StudentVerificationUpsert) SetEmail(v string) *StudentVerificationUpsert {
	u.Set(studentverification.FieldEmail, v)
	return u
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateEmail() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldEmail)
	return u
}

// SetEmailRaw sets the "email_raw" field.
func (u *StudentVerificationUpsert) SetEmailRaw(v string) *StudentVerificationUpsert {
	u.Set(studentverification.FieldEmailRaw, v)
	return u
}

// UpdateEmailRaw sets the "email_raw" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateEmailRaw() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldEmailRaw)
	return u
}

// SetStatus sets the "status" field.
func (u *StudentVerificationUpsert) SetStatus(v string) *StudentVerificationUpsert {
	u.Set(studentverification.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateStatus() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldStatus)
	return u
}

// SetVerifiedAt sets the "verified_at" field.
func (u *StudentVerificationUpsert) SetVerifiedAt(v time.Time) *StudentVerificationUpsert {
	u.Set(studentverification.FieldVerifiedAt, v)
	return u
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateVerifiedAt() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldVerifiedAt)
	return u
}

// SetExpiresAt sets the "expires_at" field.
func (u *StudentVerificationUpsert) SetExpiresAt(v time.Time) *StudentVerificationUpsert {
	u.Set(studentverification.FieldExpiresAt, v)
	return u
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateExpiresAt() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldExpiresAt)
	return u
}

// SetRevokedAt sets the "revoked_at" field.
func (u *StudentVerificationUpsert) SetRevokedAt(v time.Time) *StudentVerificationUpsert {
	u.Set(studentverification.FieldRevokedAt, v)
	return u
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateRevokedAt() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldRevokedAt)
	return u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *StudentVerificationUpsert) ClearRevokedAt() *StudentVerificationUpsert {
	u.SetNull(studentverification.FieldRevokedAt)
	return u
}

// SetRevokedBy sets the "revoked_by" field.
func (u *StudentVerificationUpsert) SetRevokedBy(v int64) *StudentVerificationUpsert {
	u.Set(studentverification.FieldRevokedBy, v)
	return u
}

// UpdateRevokedBy sets the "revoked_by" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateRevokedBy() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldRevokedBy)
	return u
}

// AddRevokedBy adds v to the "revoked_by" field.
func (u *StudentVerificationUpsert) AddRevokedBy(v int64) *StudentVerificationUpsert {
	u.Add(studentverification.FieldRevokedBy, v)
	return u
}

// ClearRevokedBy clears the value of the "revoked_by" field.
func (u *StudentVerificationUpsert) ClearRevokedBy() *StudentVerificationUpsert {
	u.SetNull(studentverification.FieldRevokedBy)
	return u
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *StudentVerificationUpsert) SetRevokeReason(v string) *StudentVerificationUpsert {
	u.Set(studentverification.FieldRevokeReason, v)
	return u
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateRevokeReason() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldRevokeReason)
	return u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (u *StudentVerificationUpsert) ClearRevokeReason() *StudentVerificationUpsert {
	u.SetNull(studentverification.FieldRevokeReason)
	return u
}

// SetRebateRateApplied sets the "rebate_rate_applied" field.
func (u *StudentVerificationUpsert) SetRebateRateApplied(v float64) *StudentVerificationUpsert {
	u.Set(studentverification.FieldRebateRateApplied, v)
	return u
}

// UpdateRebateRateApplied sets the "rebate_rate_applied" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateRebateRateApplied() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldRebateRateApplied)
	return u
}

// AddRebateRateApplied adds v to the "rebate_rate_applied" field.
func (u *StudentVerificationUpsert) AddRebateRateApplied(v float64) *StudentVerificationUpsert {
	u.Add(studentverification.FieldRebateRateApplied, v)
	return u
}

// ClearRebateRateApplied clears the value of the "rebate_rate_applied" field.
func (u *StudentVerificationUpsert) ClearRebateRateApplied() *StudentVerificationUpsert {
	u.SetNull(studentverification.FieldRebateRateApplied)
	return u
}

// SetPreviousRebateRate sets the "previous_rebate_rate" field.
func (u *StudentVerificationUpsert) SetPreviousRebateRate(v float64) *StudentVerificationUpsert {
	u.Set(studentverification.FieldPreviousRebateRate, v)
	return u
}

// UpdatePreviousRebateRate sets the "previous_rebate_rate" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdatePreviousRebateRate() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldPreviousRebateRate)
	return u
}

// AddPreviousRebateRate adds v to the "previous_rebate_rate" field.
func (u *StudentVerificationUpsert) AddPreviousRebateRate(v float64) *StudentVerificationUpsert {
	u.Add(studentverification.FieldPreviousRebateRate, v)
	return u
}

// ClearPreviousRebateRate clears the value of the "previous_rebate_rate" field.
func (u *StudentVerificationUpsert) ClearPreviousRebateRate() *StudentVerificationUpsert {
	u.SetNull(studentverification.FieldPreviousRebateRate)
	return u
}

// SetGrantedGroupIds sets the "granted_group_ids" field.
func (u *StudentVerificationUpsert) SetGrantedGroupIds(v []int64) *StudentVerificationUpsert {
	u.Set(studentverification.FieldGrantedGroupIds, v)
	return u
}

// UpdateGrantedGroupIds sets the "granted_group_ids" field to the value that was provided on create.
func (u *StudentVerificationUpsert) UpdateGrantedGroupIds() *StudentVerificationUpsert {
	u.SetExcluded(studentverification.FieldGrantedGroupIds)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.StudentVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StudentVerificationUpsertOne) UpdateNewValues() *StudentVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(studentverification.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StudentVerification.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StudentVerificationUpsertOne) Ignore() *StudentVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudentVerificationUpsertOne) DoNothing() *StudentVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudentVerificationCreate.OnConflict
// documentation for more info.
func (u *StudentVerificationUpsertOne) Update(set func(*StudentVerificationUpsert)) *StudentVerificationUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudentVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudentVerificationUpsertOne) SetUpdatedAt(v time.Time) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateUpdatedAt() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *StudentVerificationUpsertOne) SetUserID(v int64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateUserID() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *StudentVerificationUpsertOne) ClearUserID() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearUserID()
	})
}

// SetEmail sets the "email" field.
func (u *StudentVerificationUpsertOne) SetEmail(v string) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateEmail() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateEmail()
	})
}

// SetEmailRaw sets the "email_raw" field.
func (u *StudentVerificationUpsertOne) SetEmailRaw(v string) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetEmailRaw(v)
	})
}

// UpdateEmailRaw sets the "email_raw" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateEmailRaw() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateEmailRaw()
	})
}

// SetStatus sets the "status" field.
func (u *StudentVerificationUpsertOne) SetStatus(v string) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateStatus() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateStatus()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *StudentVerificationUpsertOne) SetVerifiedAt(v time.Time) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateVerifiedAt() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateVerifiedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *StudentVerificationUpsertOne) SetExpiresAt(v time.Time) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateExpiresAt() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *StudentVerificationUpsertOne) SetRevokedAt(v time.Time) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateRevokedAt() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *StudentVerificationUpsertOne) ClearRevokedAt() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokedBy sets the "revoked_by" field.
func (u *StudentVerificationUpsertOne) SetRevokedBy(v int64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRevokedBy(v)
	})
}

// AddRevokedBy adds v to the "revoked_by" field.
func (u *StudentVerificationUpsertOne) AddRevokedBy(v int64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.AddRevokedBy(v)
	})
}

// UpdateRevokedBy sets the "revoked_by" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateRevokedBy() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRevokedBy()
	})
}

// ClearRevokedBy clears the value of the "revoked_by" field.
func (u *StudentVerificationUpsertOne) ClearRevokedBy() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRevokedBy()
	})
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *StudentVerificationUpsertOne) SetRevokeReason(v string) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRevokeReason(v)
	})
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateRevokeReason() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRevokeReason()
	})
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (u *StudentVerificationUpsertOne) ClearRevokeReason() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRevokeReason()
	})
}

// SetRebateRateApplied sets the "rebate_rate_applied" field.
func (u *StudentVerificationUpsertOne) SetRebateRateApplied(v float64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRebateRateApplied(v)
	})
}

// AddRebateRateApplied adds v to the "rebate_rate_applied" field.
func (u *StudentVerificationUpsertOne) AddRebateRateApplied(v float64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.AddRebateRateApplied(v)
	})
}

// UpdateRebateRateApplied sets the "rebate_rate_applied" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateRebateRateApplied() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRebateRateApplied()
	})
}

// ClearRebateRateApplied clears the value of the "rebate_rate_applied" field.
func (u *StudentVerificationUpsertOne) ClearRebateRateApplied() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRebateRateApplied()
	})
}

// SetPreviousRebateRate sets the "previous_rebate_rate" field.
func (u *StudentVerificationUpsertOne) SetPreviousRebateRate(v float64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetPreviousRebateRate(v)
	})
}

// AddPreviousRebateRate adds v to the "previous_rebate_rate" field.
func (u *StudentVerificationUpsertOne) AddPreviousRebateRate(v float64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.AddPreviousRebateRate(v)
	})
}

// UpdatePreviousRebateRate sets the "previous_rebate_rate" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdatePreviousRebateRate() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdatePreviousRebateRate()
	})
}

// ClearPreviousRebateRate clears the value of the "previous_rebate_rate" field.
func (u *StudentVerificationUpsertOne) ClearPreviousRebateRate() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearPreviousRebateRate()
	})
}

// SetGrantedGroupIds sets the "granted_group_ids" field.
func (u *StudentVerificationUpsertOne) SetGrantedGroupIds(v []int64) *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetGrantedGroupIds(v)
	})
}

// UpdateGrantedGroupIds sets the "granted_group_ids" field to the value that was provided on create.
func (u *StudentVerificationUpsertOne) UpdateGrantedGroupIds() *StudentVerificationUpsertOne {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateGrantedGroupIds()
	})
}

// Exec executes the query.
func (u *StudentVerificationUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StudentVerificationCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudentVerificationUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StudentVerificationUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StudentVerificationUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StudentVerificationCreateBulk is the builder for creating many StudentVerification entities in bulk.
type StudentVerificationCreateBulk struct {
	config
	err      error
	builders []*StudentVerificationCreate
	conflict []sql.ConflictOption
}

// Save creates the StudentVerification entities in the database.
func (_c *StudentVerificationCreateBulk) Save(ctx context.Context) ([]*StudentVerification, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StudentVerification, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StudentVerificationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StudentVerificationCreateBulk) SaveX(ctx context.Context) []*StudentVerification {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StudentVerificationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StudentVerificationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StudentVerification.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StudentVerificationUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *StudentVerificationCreateBulk) OnConflict(opts ...sql.ConflictOption) *StudentVerificationUpsertBulk {
	_c.conflict = opts
	return &StudentVerificationUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StudentVerification.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StudentVerificationCreateBulk) OnConflictColumns(columns ...string) *StudentVerificationUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StudentVerificationUpsertBulk{
		create: _c,
	}
}

// StudentVerificationUpsertBulk is the builder for "upsert"-ing
// a bulk of StudentVerification nodes.
type StudentVerificationUpsertBulk struct {
	create *StudentVerificationCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StudentVerification.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *StudentVerificationUpsertBulk) UpdateNewValues() *StudentVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(studentverification.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StudentVerification.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StudentVerificationUpsertBulk) Ignore() *StudentVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StudentVerificationUpsertBulk) DoNothing() *StudentVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StudentVerificationCreateBulk.OnConflict
// documentation for more info.
func (u *StudentVerificationUpsertBulk) Update(set func(*StudentVerificationUpsert)) *StudentVerificationUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StudentVerificationUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *StudentVerificationUpsertBulk) SetUpdatedAt(v time.Time) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateUpdatedAt() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *StudentVerificationUpsertBulk) SetUserID(v int64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateUserID() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateUserID()
	})
}

// ClearUserID clears the value of the "user_id" field.
func (u *StudentVerificationUpsertBulk) ClearUserID() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearUserID()
	})
}

// SetEmail sets the "email" field.
func (u *StudentVerificationUpsertBulk) SetEmail(v string) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetEmail(v)
	})
}

// UpdateEmail sets the "email" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateEmail() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateEmail()
	})
}

// SetEmailRaw sets the "email_raw" field.
func (u *StudentVerificationUpsertBulk) SetEmailRaw(v string) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetEmailRaw(v)
	})
}

// UpdateEmailRaw sets the "email_raw" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateEmailRaw() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateEmailRaw()
	})
}

// SetStatus sets the "status" field.
func (u *StudentVerificationUpsertBulk) SetStatus(v string) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateStatus() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateStatus()
	})
}

// SetVerifiedAt sets the "verified_at" field.
func (u *StudentVerificationUpsertBulk) SetVerifiedAt(v time.Time) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetVerifiedAt(v)
	})
}

// UpdateVerifiedAt sets the "verified_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateVerifiedAt() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateVerifiedAt()
	})
}

// SetExpiresAt sets the "expires_at" field.
func (u *StudentVerificationUpsertBulk) SetExpiresAt(v time.Time) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetExpiresAt(v)
	})
}

// UpdateExpiresAt sets the "expires_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateExpiresAt() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateExpiresAt()
	})
}

// SetRevokedAt sets the "revoked_at" field.
func (u *StudentVerificationUpsertBulk) SetRevokedAt(v time.Time) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRevokedAt(v)
	})
}

// UpdateRevokedAt sets the "revoked_at" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateRevokedAt() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRevokedAt()
	})
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (u *StudentVerificationUpsertBulk) ClearRevokedAt() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRevokedAt()
	})
}

// SetRevokedBy sets the "revoked_by" field.
func (u *StudentVerificationUpsertBulk) SetRevokedBy(v int64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRevokedBy(v)
	})
}

// AddRevokedBy adds v to the "revoked_by" field.
func (u *StudentVerificationUpsertBulk) AddRevokedBy(v int64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.AddRevokedBy(v)
	})
}

// UpdateRevokedBy sets the "revoked_by" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateRevokedBy() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRevokedBy()
	})
}

// ClearRevokedBy clears the value of the "revoked_by" field.
func (u *StudentVerificationUpsertBulk) ClearRevokedBy() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRevokedBy()
	})
}

// SetRevokeReason sets the "revoke_reason" field.
func (u *StudentVerificationUpsertBulk) SetRevokeReason(v string) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRevokeReason(v)
	})
}

// UpdateRevokeReason sets the "revoke_reason" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateRevokeReason() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRevokeReason()
	})
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (u *StudentVerificationUpsertBulk) ClearRevokeReason() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRevokeReason()
	})
}

// SetRebateRateApplied sets the "rebate_rate_applied" field.
func (u *StudentVerificationUpsertBulk) SetRebateRateApplied(v float64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetRebateRateApplied(v)
	})
}

// AddRebateRateApplied adds v to the "rebate_rate_applied" field.
func (u *StudentVerificationUpsertBulk) AddRebateRateApplied(v float64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.AddRebateRateApplied(v)
	})
}

// UpdateRebateRateApplied sets the "rebate_rate_applied" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateRebateRateApplied() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateRebateRateApplied()
	})
}

// ClearRebateRateApplied clears the value of the "rebate_rate_applied" field.
func (u *StudentVerificationUpsertBulk) ClearRebateRateApplied() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearRebateRateApplied()
	})
}

// SetPreviousRebateRate sets the "previous_rebate_rate" field.
func (u *StudentVerificationUpsertBulk) SetPreviousRebateRate(v float64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetPreviousRebateRate(v)
	})
}

// AddPreviousRebateRate adds v to the "previous_rebate_rate" field.
func (u *StudentVerificationUpsertBulk) AddPreviousRebateRate(v float64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.AddPreviousRebateRate(v)
	})
}

// UpdatePreviousRebateRate sets the "previous_rebate_rate" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdatePreviousRebateRate() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdatePreviousRebateRate()
	})
}

// ClearPreviousRebateRate clears the value of the "previous_rebate_rate" field.
func (u *StudentVerificationUpsertBulk) ClearPreviousRebateRate() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.ClearPreviousRebateRate()
	})
}

// SetGrantedGroupIds sets the "granted_group_ids" field.
func (u *StudentVerificationUpsertBulk) SetGrantedGroupIds(v []int64) *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.SetGrantedGroupIds(v)
	})
}

// UpdateGrantedGroupIds sets the "granted_group_ids" field to the value that was provided on create.
func (u *StudentVerificationUpsertBulk) UpdateGrantedGroupIds() *StudentVerificationUpsertBulk {
	return u.Update(func(s *StudentVerificationUpsert) {
		s.UpdateGrantedGroupIds()
	})
}

// Exec executes the query.
func (u *StudentVerificationUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StudentVerificationCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StudentVerificationCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StudentVerificationUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
