// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/studentverification"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// StudentVerificationUpdate is the builder for updating StudentVerification entities.
type StudentVerificationUpdate struct {
	config
	hooks    []Hook
	mutation *StudentVerificationMutation
}

// Where appends a list predicates to the StudentVerificationUpdate builder.
func (_u *StudentVerificationUpdate) Where(ps ...predicate.StudentVerification) *StudentVerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StudentVerificationUpdate) SetUpdatedAt(v time.Time) *StudentVerificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *StudentVerificationUpdate) SetUserID(v int64) *StudentVerificationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableUserID(v *int64) *StudentVerificationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *StudentVerificationUpdate) ClearUserID() *StudentVerificationUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *StudentVerificationUpdate) SetEmail(v string) *StudentVerificationUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableEmail(v *string) *StudentVerificationUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetEmailRaw sets the "email_raw" field.
func (_u *StudentVerificationUpdate) SetEmailRaw(v string) *StudentVerificationUpdate {
	_u.mutation.SetEmailRaw(v)
	return _u
}

// SetNillableEmailRaw sets the "email_raw" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableEmailRaw(v *string) *StudentVerificationUpdate {
	if v != nil {
		_u.SetEmailRaw(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StudentVerificationUpdate) SetStatus(v string) *StudentVerificationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableStatus(v *string) *StudentVerificationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *StudentVerificationUpdate) SetVerifiedAt(v time.Time) *StudentVerificationUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableVerifiedAt(v *time.Time) *StudentVerificationUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *StudentVerificationUpdate) SetExpiresAt(v time.Time) *StudentVerificationUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableExpiresAt(v *time.Time) *StudentVerificationUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *StudentVerificationUpdate) SetRevokedAt(v time.Time) *StudentVerificationUpdate {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableRevokedAt(v *time.Time) *StudentVerificationUpdate {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *StudentVerificationUpdate) ClearRevokedAt() *StudentVerificationUpdate {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedBy sets the "revoked_by" field.
func (_u *StudentVerificationUpdate) SetRevokedBy(v int64) *StudentVerificationUpdate {
	_u.mutation.ResetRevokedBy()
	_u.mutation.SetRevokedBy(v)
	return _u
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableRevokedBy(v *int64) *StudentVerificationUpdate {
	if v != nil {
		_u.SetRevokedBy(*v)
	}
	return _u
}

// AddRevokedBy adds value to the "revoked_by" field.
func (_u *StudentVerificationUpdate) AddRevokedBy(v int64) *StudentVerificationUpdate {
	_u.mutation.AddRevokedBy(v)
	return _u
}

// ClearRevokedBy clears the value of the "revoked_by" field.
func (_u *StudentVerificationUpdate) ClearRevokedBy() *StudentVerificationUpdate {
	_u.mutation.ClearRevokedBy()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *StudentVerificationUpdate) SetRevokeReason(v string) *StudentVerificationUpdate {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableRevokeReason(v *string) *StudentVerificationUpdate {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (_u *StudentVerificationUpdate) ClearRevokeReason() *StudentVerificationUpdate {
	_u.mutation.ClearRevokeReason()
	return _u
}

// SetRebateRateApplied sets the "rebate_rate_applied" field.
func (_u *StudentVerificationUpdate) SetRebateRateApplied(v float64) *StudentVerificationUpdate {
	_u.mutation.ResetRebateRateApplied()
	_u.mutation.SetRebateRateApplied(v)
	return _u
}

// SetNillableRebateRateApplied sets the "rebate_rate_applied" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillableRebateRateApplied(v *float64) *StudentVerificationUpdate {
	if v != nil {
		_u.SetRebateRateApplied(*v)
	}
	return _u
}

// AddRebateRateApplied adds value to the "rebate_rate_applied" field.
func (_u *StudentVerificationUpdate) AddRebateRateApplied(v float64) *StudentVerificationUpdate {
	_u.mutation.AddRebateRateApplied(v)
	return _u
}

// ClearRebateRateApplied clears the value of the "rebate_rate_applied" field.
func (_u *StudentVerificationUpdate) ClearRebateRateApplied() *StudentVerificationUpdate {
	_u.mutation.ClearRebateRateApplied()
	return _u
}

// SetPreviousRebateRate sets the "previous_rebate_rate" field.
func (_u *StudentVerificationUpdate) SetPreviousRebateRate(v float64) *StudentVerificationUpdate {
	_u.mutation.ResetPreviousRebateRate()
	_u.mutation.SetPreviousRebateRate(v)
	return _u
}

// SetNillablePreviousRebateRate sets the "previous_rebate_rate" field if the given value is not nil.
func (_u *StudentVerificationUpdate) SetNillablePreviousRebateRate(v *float64) *StudentVerificationUpdate {
	if v != nil {
		_u.SetPreviousRebateRate(*v)
	}
	return _u
}

// AddPreviousRebateRate adds value to the "previous_rebate_rate" field.
func (_u *StudentVerificationUpdate) AddPreviousRebateRate(v float64) *StudentVerificationUpdate {
	_u.mutation.AddPreviousRebateRate(v)
	return _u
}

// ClearPreviousRebateRate clears the value of the "previous_rebate_rate" field.
func (_u *StudentVerificationUpdate) ClearPreviousRebateRate() *StudentVerificationUpdate {
	_u.mutation.ClearPreviousRebateRate()
	return _u
}

// SetGrantedGroupIds sets the "granted_group_ids" field.
func (_u *StudentVerificationUpdate) SetGrantedGroupIds(v []int64) *StudentVerificationUpdate {
	_u.mutation.SetGrantedGroupIds(v)
	return _u
}

// AppendGrantedGroupIds appends value to the "granted_group_ids" field.
func (_u *StudentVerificationUpdate) AppendGrantedGroupIds(v []int64) *StudentVerificationUpdate {
	_u.mutation.AppendGrantedGroupIds(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *StudentVerificationUpdate) SetUser(v *User) *StudentVerificationUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the StudentVerificationMutation object of the builder.
func (_u *StudentVerificationUpdate) Mutation() *StudentVerificationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *StudentVerificationUpdate) ClearUser() *StudentVerificationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StudentVerificationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudentVerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StudentVerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudentVerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StudentVerificationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := studentverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StudentVerificationUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := studentverification.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmailRaw(); ok {
		if err := studentverification.EmailRawValidator(v); err != nil {
			return &ValidationError{Name: "email_raw", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.email_raw": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := studentverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StudentVerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(studentverification.Table, studentverification.Columns, sqlgraph.NewFieldSpec(studentverification.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(studentverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(studentverification.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailRaw(); ok {
		_spec.SetField(studentverification.FieldEmailRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(studentverification.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(studentverification.FieldVerifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(studentverification.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(studentverification.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(studentverification.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedBy(); ok {
		_spec.SetField(studentverification.FieldRevokedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevokedBy(); ok {
		_spec.AddField(studentverification.FieldRevokedBy, field.TypeInt64, value)
	}
	if _u.mutation.RevokedByCleared() {
		_spec.ClearField(studentverification.FieldRevokedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(studentverification.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.RevokeReasonCleared() {
		_spec.ClearField(studentverification.FieldRevokeReason, field.TypeString)
	}
	if value, ok := _u.mutation.RebateRateApplied(); ok {
		_spec.SetField(studentverification.FieldRebateRateApplied, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRebateRateApplied(); ok {
		_spec.AddField(studentverification.FieldRebateRateApplied, field.TypeFloat64, value)
	}
	if _u.mutation.RebateRateAppliedCleared() {
		_spec.ClearField(studentverification.FieldRebateRateApplied, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PreviousRebateRate(); ok {
		_spec.SetField(studentverification.FieldPreviousRebateRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousRebateRate(); ok {
		_spec.AddField(studentverification.FieldPreviousRebateRate, field.TypeFloat64, value)
	}
	if _u.mutation.PreviousRebateRateCleared() {
		_spec.ClearField(studentverification.FieldPreviousRebateRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GrantedGroupIds(); ok {
		_spec.SetField(studentverification.FieldGrantedGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, studentverification.FieldGrantedGroupIds, value)
		})
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   studentverification.UserTable,
			Columns: []string{studentverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   studentverification.UserTable,
			Columns: []string{studentverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studentverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StudentVerificationUpdateOne is the builder for updating a single StudentVerification entity.
type StudentVerificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StudentVerificationMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StudentVerificationUpdateOne) SetUpdatedAt(v time.Time) *StudentVerificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *StudentVerificationUpdateOne) SetUserID(v int64) *StudentVerificationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableUserID(v *int64) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *StudentVerificationUpdateOne) ClearUserID() *StudentVerificationUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetEmail sets the "email" field.
func (_u *StudentVerificationUpdateOne) SetEmail(v string) *StudentVerificationUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableEmail(v *string) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetEmailRaw sets the "email_raw" field.
func (_u *StudentVerificationUpdateOne) SetEmailRaw(v string) *StudentVerificationUpdateOne {
	_u.mutation.SetEmailRaw(v)
	return _u
}

// SetNillableEmailRaw sets the "email_raw" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableEmailRaw(v *string) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetEmailRaw(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *StudentVerificationUpdateOne) SetStatus(v string) *StudentVerificationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableStatus(v *string) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetVerifiedAt sets the "verified_at" field.
func (_u *StudentVerificationUpdateOne) SetVerifiedAt(v time.Time) *StudentVerificationUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableVerifiedAt(v *time.Time) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
	}
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *StudentVerificationUpdateOne) SetExpiresAt(v time.Time) *StudentVerificationUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableExpiresAt(v *time.Time) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetRevokedAt sets the "revoked_at" field.
func (_u *StudentVerificationUpdateOne) SetRevokedAt(v time.Time) *StudentVerificationUpdateOne {
	_u.mutation.SetRevokedAt(v)
	return _u
}

// SetNillableRevokedAt sets the "revoked_at" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableRevokedAt(v *time.Time) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetRevokedAt(*v)
	}
	return _u
}

// ClearRevokedAt clears the value of the "revoked_at" field.
func (_u *StudentVerificationUpdateOne) ClearRevokedAt() *StudentVerificationUpdateOne {
	_u.mutation.ClearRevokedAt()
	return _u
}

// SetRevokedBy sets the "revoked_by" field.
func (_u *StudentVerificationUpdateOne) SetRevokedBy(v int64) *StudentVerificationUpdateOne {
	_u.mutation.ResetRevokedBy()
	_u.mutation.SetRevokedBy(v)
	return _u
}

// SetNillableRevokedBy sets the "revoked_by" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableRevokedBy(v *int64) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetRevokedBy(*v)
	}
	return _u
}

// AddRevokedBy adds value to the "revoked_by" field.
func (_u *StudentVerificationUpdateOne) AddRevokedBy(v int64) *StudentVerificationUpdateOne {
	_u.mutation.AddRevokedBy(v)
	return _u
}

// ClearRevokedBy clears the value of the "revoked_by" field.
func (_u *StudentVerificationUpdateOne) ClearRevokedBy() *StudentVerificationUpdateOne {
	_u.mutation.ClearRevokedBy()
	return _u
}

// SetRevokeReason sets the "revoke_reason" field.
func (_u *StudentVerificationUpdateOne) SetRevokeReason(v string) *StudentVerificationUpdateOne {
	_u.mutation.SetRevokeReason(v)
	return _u
}

// SetNillableRevokeReason sets the "revoke_reason" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableRevokeReason(v *string) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetRevokeReason(*v)
	}
	return _u
}

// ClearRevokeReason clears the value of the "revoke_reason" field.
func (_u *StudentVerificationUpdateOne) ClearRevokeReason() *StudentVerificationUpdateOne {
	_u.mutation.ClearRevokeReason()
	return _u
}

// SetRebateRateApplied sets the "rebate_rate_applied" field.
func (_u *StudentVerificationUpdateOne) SetRebateRateApplied(v float64) *StudentVerificationUpdateOne {
	_u.mutation.ResetRebateRateApplied()
	_u.mutation.SetRebateRateApplied(v)
	return _u
}

// SetNillableRebateRateApplied sets the "rebate_rate_applied" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillableRebateRateApplied(v *float64) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetRebateRateApplied(*v)
	}
	return _u
}

// AddRebateRateApplied adds value to the "rebate_rate_applied" field.
func (_u *StudentVerificationUpdateOne) AddRebateRateApplied(v float64) *StudentVerificationUpdateOne {
	_u.mutation.AddRebateRateApplied(v)
	return _u
}

// ClearRebateRateApplied clears the value of the "rebate_rate_applied" field.
func (_u *StudentVerificationUpdateOne) ClearRebateRateApplied() *StudentVerificationUpdateOne {
	_u.mutation.ClearRebateRateApplied()
	return _u
}

// SetPreviousRebateRate sets the "previous_rebate_rate" field.
func (_u *StudentVerificationUpdateOne) SetPreviousRebateRate(v float64) *StudentVerificationUpdateOne {
	_u.mutation.ResetPreviousRebateRate()
	_u.mutation.SetPreviousRebateRate(v)
	return _u
}

// SetNillablePreviousRebateRate sets the "previous_rebate_rate" field if the given value is not nil.
func (_u *StudentVerificationUpdateOne) SetNillablePreviousRebateRate(v *float64) *StudentVerificationUpdateOne {
	if v != nil {
		_u.SetPreviousRebateRate(*v)
	}
	return _u
}

// AddPreviousRebateRate adds value to the "previous_rebate_rate" field.
func (_u *StudentVerificationUpdateOne) AddPreviousRebateRate(v float64) *StudentVerificationUpdateOne {
	_u.mutation.AddPreviousRebateRate(v)
	return _u
}

// ClearPreviousRebateRate clears the value of the "previous_rebate_rate" field.
func (_u *StudentVerificationUpdateOne) ClearPreviousRebateRate() *StudentVerificationUpdateOne {
	_u.mutation.ClearPreviousRebateRate()
	return _u
}

// SetGrantedGroupIds sets the "granted_group_ids" field.
func (_u *StudentVerificationUpdateOne) SetGrantedGroupIds(v []int64) *StudentVerificationUpdateOne {
	_u.mutation.SetGrantedGroupIds(v)
	return _u
}

// AppendGrantedGroupIds appends value to the "granted_group_ids" field.
func (_u *StudentVerificationUpdateOne) AppendGrantedGroupIds(v []int64) *StudentVerificationUpdateOne {
	_u.mutation.AppendGrantedGroupIds(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *StudentVerificationUpdateOne) SetUser(v *User) *StudentVerificationUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the StudentVerificationMutation object of the builder.
func (_u *StudentVerificationUpdateOne) Mutation() *StudentVerificationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *StudentVerificationUpdateOne) ClearUser() *StudentVerificationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the StudentVerificationUpdate builder.
func (_u *StudentVerificationUpdateOne) Where(ps ...predicate.StudentVerification) *StudentVerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StudentVerificationUpdateOne) Select(field string, fields ...string) *StudentVerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StudentVerification entity.
func (_u *StudentVerificationUpdateOne) Save(ctx context.Context) (*StudentVerification, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StudentVerificationUpdateOne) SaveX(ctx context.Context) *StudentVerification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StudentVerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StudentVerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *StudentVerificationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := studentverification.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StudentVerificationUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := studentverification.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.EmailRaw(); ok {
		if err := studentverification.EmailRawValidator(v); err != nil {
			return &ValidationError{Name: "email_raw", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.email_raw": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := studentverification.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "StudentVerification.status": %w`, err)}
		}
	}
	return nil
}

func (_u *StudentVerificationUpdateOne) sqlSave(ctx context.Context) (_node *StudentVerification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(studentverification.Table, studentverification.Columns, sqlgraph.NewFieldSpec(studentverification.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StudentVerification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, studentverification.FieldID)
		for _, f := range fields {
			if !studentverification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != studentverification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(studentverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(studentverification.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.EmailRaw(); ok {
		_spec.SetField(studentverification.FieldEmailRaw, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(studentverification.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(studentverification.FieldVerifiedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(studentverification.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RevokedAt(); ok {
		_spec.SetField(studentverification.FieldRevokedAt, field.TypeTime, value)
	}
	if _u.mutation.RevokedAtCleared() {
		_spec.ClearField(studentverification.FieldRevokedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.RevokedBy(); ok {
		_spec.SetField(studentverification.FieldRevokedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedRevokedBy(); ok {
		_spec.AddField(studentverification.FieldRevokedBy, field.TypeInt64, value)
	}
	if _u.mutation.RevokedByCleared() {
		_spec.ClearField(studentverification.FieldRevokedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.RevokeReason(); ok {
		_spec.SetField(studentverification.FieldRevokeReason, field.TypeString, value)
	}
	if _u.mutation.RevokeReasonCleared() {
		_spec.ClearField(studentverification.FieldRevokeReason, field.TypeString)
	}
	if value, ok := _u.mutation.RebateRateApplied(); ok {
		_spec.SetField(studentverification.FieldRebateRateApplied, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRebateRateApplied(); ok {
		_spec.AddField(studentverification.FieldRebateRateApplied, field.TypeFloat64, value)
	}
	if _u.mutation.RebateRateAppliedCleared() {
		_spec.ClearField(studentverification.FieldRebateRateApplied, field.TypeFloat64)
	}
	if value, ok := _u.mutation.PreviousRebateRate(); ok {
		_spec.SetField(studentverification.FieldPreviousRebateRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPreviousRebateRate(); ok {
		_spec.AddField(studentverification.FieldPreviousRebateRate, field.TypeFloat64, value)
	}
	if _u.mutation.PreviousRebateRateCleared() {
		_spec.ClearField(studentverification.FieldPreviousRebateRate, field.TypeFloat64)
	}
	if value, ok := _u.mutation.GrantedGroupIds(); ok {
		_spec.SetField(studentverification.FieldGrantedGroupIds, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedGrantedGroupIds(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, studentverification.FieldGrantedGroupIds, value)
		})
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   studentverification.UserTable,
			Columns: []string{studentverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   studentverification.UserTable,
			Columns: []string{studentverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StudentVerification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{studentverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
