// Code generated by ent, DO NOT EDIT.

package prompttemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldDescription, v))
}

// SourceURL applies equality check predicate on the "source_url" field. It's identical to SourceURLEQ.
func SourceURL(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldSourceURL, v))
}

// SourceNote applies equality check predicate on the "source_note" field. It's identical to SourceNoteEQ.
func SourceNote(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldSourceNote, v))
}

// ArchivedAt applies equality check predicate on the "archived_at" field. It's identical to ArchivedAtEQ.
func ArchivedAt(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldArchivedAt, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldRevision, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContainsFold(FieldDescription, v))
}

// SourceURLEQ applies the EQ predicate on the "source_url" field.
func SourceURLEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldSourceURL, v))
}

// SourceURLNEQ applies the NEQ predicate on the "source_url" field.
func SourceURLNEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldSourceURL, v))
}

// SourceURLIn applies the In predicate on the "source_url" field.
func SourceURLIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldSourceURL, vs...))
}

// SourceURLNotIn applies the NotIn predicate on the "source_url" field.
func SourceURLNotIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldSourceURL, vs...))
}

// SourceURLGT applies the GT predicate on the "source_url" field.
func SourceURLGT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldSourceURL, v))
}

// SourceURLGTE applies the GTE predicate on the "source_url" field.
func SourceURLGTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldSourceURL, v))
}

// SourceURLLT applies the LT predicate on the "source_url" field.
func SourceURLLT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldSourceURL, v))
}

// SourceURLLTE applies the LTE predicate on the "source_url" field.
func SourceURLLTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldSourceURL, v))
}

// SourceURLContains applies the Contains predicate on the "source_url" field.
func SourceURLContains(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContains(FieldSourceURL, v))
}

// SourceURLHasPrefix applies the HasPrefix predicate on the "source_url" field.
func SourceURLHasPrefix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasPrefix(FieldSourceURL, v))
}

// SourceURLHasSuffix applies the HasSuffix predicate on the "source_url" field.
func SourceURLHasSuffix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasSuffix(FieldSourceURL, v))
}

// SourceURLIsNil applies the IsNil predicate on the "source_url" field.
func SourceURLIsNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIsNull(FieldSourceURL))
}

// SourceURLNotNil applies the NotNil predicate on the "source_url" field.
func SourceURLNotNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotNull(FieldSourceURL))
}

// SourceURLEqualFold applies the EqualFold predicate on the "source_url" field.
func SourceURLEqualFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEqualFold(FieldSourceURL, v))
}

// SourceURLContainsFold applies the ContainsFold predicate on the "source_url" field.
func SourceURLContainsFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContainsFold(FieldSourceURL, v))
}

// SourceNoteEQ applies the EQ predicate on the "source_note" field.
func SourceNoteEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldSourceNote, v))
}

// SourceNoteNEQ applies the NEQ predicate on the "source_note" field.
func SourceNoteNEQ(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldSourceNote, v))
}

// SourceNoteIn applies the In predicate on the "source_note" field.
func SourceNoteIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldSourceNote, vs...))
}

// SourceNoteNotIn applies the NotIn predicate on the "source_note" field.
func SourceNoteNotIn(vs ...string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldSourceNote, vs...))
}

// SourceNoteGT applies the GT predicate on the "source_note" field.
func SourceNoteGT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldSourceNote, v))
}

// SourceNoteGTE applies the GTE predicate on the "source_note" field.
func SourceNoteGTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldSourceNote, v))
}

// SourceNoteLT applies the LT predicate on the "source_note" field.
func SourceNoteLT(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldSourceNote, v))
}

// SourceNoteLTE applies the LTE predicate on the "source_note" field.
func SourceNoteLTE(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldSourceNote, v))
}

// SourceNoteContains applies the Contains predicate on the "source_note" field.
func SourceNoteContains(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContains(FieldSourceNote, v))
}

// SourceNoteHasPrefix applies the HasPrefix predicate on the "source_note" field.
func SourceNoteHasPrefix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasPrefix(FieldSourceNote, v))
}

// SourceNoteHasSuffix applies the HasSuffix predicate on the "source_note" field.
func SourceNoteHasSuffix(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldHasSuffix(FieldSourceNote, v))
}

// SourceNoteIsNil applies the IsNil predicate on the "source_note" field.
func SourceNoteIsNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIsNull(FieldSourceNote))
}

// SourceNoteNotNil applies the NotNil predicate on the "source_note" field.
func SourceNoteNotNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotNull(FieldSourceNote))
}

// SourceNoteEqualFold applies the EqualFold predicate on the "source_note" field.
func SourceNoteEqualFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEqualFold(FieldSourceNote, v))
}

// SourceNoteContainsFold applies the ContainsFold predicate on the "source_note" field.
func SourceNoteContainsFold(v string) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldContainsFold(FieldSourceNote, v))
}

// ArchivedAtEQ applies the EQ predicate on the "archived_at" field.
func ArchivedAtEQ(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldArchivedAt, v))
}

// ArchivedAtNEQ applies the NEQ predicate on the "archived_at" field.
func ArchivedAtNEQ(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldArchivedAt, v))
}

// ArchivedAtIn applies the In predicate on the "archived_at" field.
func ArchivedAtIn(vs ...time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldArchivedAt, vs...))
}

// ArchivedAtNotIn applies the NotIn predicate on the "archived_at" field.
func ArchivedAtNotIn(vs ...time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldArchivedAt, vs...))
}

// ArchivedAtGT applies the GT predicate on the "archived_at" field.
func ArchivedAtGT(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldArchivedAt, v))
}

// ArchivedAtGTE applies the GTE predicate on the "archived_at" field.
func ArchivedAtGTE(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldArchivedAt, v))
}

// ArchivedAtLT applies the LT predicate on the "archived_at" field.
func ArchivedAtLT(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldArchivedAt, v))
}

// ArchivedAtLTE applies the LTE predicate on the "archived_at" field.
func ArchivedAtLTE(v time.Time) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldArchivedAt, v))
}

// ArchivedAtIsNil applies the IsNil predicate on the "archived_at" field.
func ArchivedAtIsNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIsNull(FieldArchivedAt))
}

// ArchivedAtNotNil applies the NotNil predicate on the "archived_at" field.
func ArchivedAtNotNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotNull(FieldArchivedAt))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldRevision, vs...))
}

// RevisionGT applies the GT predicate on the "revision" field.
func RevisionGT(v int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldRevision, v))
}

// RevisionGTE applies the GTE predicate on the "revision" field.
func RevisionGTE(v int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldRevision, v))
}

// RevisionLT applies the LT predicate on the "revision" field.
func RevisionLT(v int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldRevision, v))
}

// RevisionLTE applies the LTE predicate on the "revision" field.
func RevisionLTE(v int) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldRevision, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotNull(FieldCreatedBy))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v int64) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.FieldNotNull(FieldUpdatedBy))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PromptTemplate) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PromptTemplate) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PromptTemplate) predicate.PromptTemplate {
	return predicate.PromptTemplate(sql.NotPredicates(p))
}
