// Code generated by ent, DO NOT EDIT.

package promptrequestevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the promptrequestevent type in the database.
	Label = "prompt_request_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldAttemptNo holds the string denoting the attempt_no field in the database.
	FieldAttemptNo = "attempt_no"
	// FieldGroupID holds the string denoting the group_id field in the database.
	FieldGroupID = "group_id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldClientModel holds the string denoting the client_model field in the database.
	FieldClientModel = "client_model"
	// FieldUpstreamModel holds the string denoting the upstream_model field in the database.
	FieldUpstreamModel = "upstream_model"
	// FieldOutboundProfile holds the string denoting the outbound_profile field in the database.
	FieldOutboundProfile = "outbound_profile"
	// FieldBindingSource holds the string denoting the binding_source field in the database.
	FieldBindingSource = "binding_source"
	// FieldVersionID holds the string denoting the version_id field in the database.
	FieldVersionID = "version_id"
	// FieldManifestSha256 holds the string denoting the manifest_sha256 field in the database.
	FieldManifestSha256 = "manifest_sha256"
	// FieldApplied holds the string denoting the applied field in the database.
	FieldApplied = "applied"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldAddedBytes holds the string denoting the added_bytes field in the database.
	FieldAddedBytes = "added_bytes"
	// FieldApplyDurationMs holds the string denoting the apply_duration_ms field in the database.
	FieldApplyDurationMs = "apply_duration_ms"
	// Table holds the table name of the promptrequestevent in the database.
	Table = "prompt_request_events"
)

// Columns holds all SQL columns for promptrequestevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRequestID,
	FieldAttemptNo,
	FieldGroupID,
	FieldAccountID,
	FieldClientModel,
	FieldUpstreamModel,
	FieldOutboundProfile,
	FieldBindingSource,
	FieldVersionID,
	FieldManifestSha256,
	FieldApplied,
	FieldReason,
	FieldAddedBytes,
	FieldApplyDurationMs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultAttemptNo holds the default value on creation for the "attempt_no" field.
	DefaultAttemptNo int
	// ClientModelValidator is a validator for the "client_model" field. It is called by the builders before save.
	ClientModelValidator func(string) error
	// UpstreamModelValidator is a validator for the "upstream_model" field. It is called by the builders before save.
	UpstreamModelValidator func(string) error
	// OutboundProfileValidator is a validator for the "outbound_profile" field. It is called by the builders before save.
	OutboundProfileValidator func(string) error
	// BindingSourceValidator is a validator for the "binding_source" field. It is called by the builders before save.
	BindingSourceValidator func(string) error
	// ManifestSha256Validator is a validator for the "manifest_sha256" field. It is called by the builders before save.
	ManifestSha256Validator func(string) error
	// DefaultApplied holds the default value on creation for the "applied" field.
	DefaultApplied bool
	// ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	ReasonValidator func(string) error
	// DefaultAddedBytes holds the default value on creation for the "added_bytes" field.
	DefaultAddedBytes int
	// DefaultApplyDurationMs holds the default value on creation for the "apply_duration_ms" field.
	DefaultApplyDurationMs int
)

// OrderOption defines the ordering options for the PromptRequestEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByAttemptNo orders the results by the attempt_no field.
func ByAttemptNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptNo, opts...).ToFunc()
}

// ByGroupID orders the results by the group_id field.
func ByGroupID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByClientModel orders the results by the client_model field.
func ByClientModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClientModel, opts...).ToFunc()
}

// ByUpstreamModel orders the results by the upstream_model field.
func ByUpstreamModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpstreamModel, opts...).ToFunc()
}

// ByOutboundProfile orders the results by the outbound_profile field.
func ByOutboundProfile(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOutboundProfile, opts...).ToFunc()
}

// ByBindingSource orders the results by the binding_source field.
func ByBindingSource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBindingSource, opts...).ToFunc()
}

// ByVersionID orders the results by the version_id field.
func ByVersionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionID, opts...).ToFunc()
}

// ByManifestSha256 orders the results by the manifest_sha256 field.
func ByManifestSha256(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldManifestSha256, opts...).ToFunc()
}

// ByApplied orders the results by the applied field.
func ByApplied(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplied, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByAddedBytes orders the results by the added_bytes field.
func ByAddedBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAddedBytes, opts...).ToFunc()
}

// ByApplyDurationMs orders the results by the apply_duration_ms field.
func ByApplyDurationMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplyDurationMs, opts...).ToFunc()
}
